cmake_minimum_required(VERSION 3.15 FATAL_ERROR)
project(CppIndMach012)
set(CMAKE_DEBUG_POSTFIX "d")
set(CMAKE_RELEASE_PREFIX "")
SET(USE_SYSTEM_EIGEN ON CACHE BOOL "Use system Eigen3; set to OFF to download using CMake's FetchContent.")
SET(DSS_EXTENSIONS OFF CACHE BOOL "If building for distribution on DSS-Extensions, enable this. It tweaks the output folders.")

SET(CMAKE_CXX_STANDARD 17)

# Handle Eigen3
# Eigen3 is a header-only library, no building necessary
if(USE_SYSTEM_EIGEN)
    find_package(Eigen3 REQUIRED)
else()
    include(FetchContent)
    set(TARGET_EIGEN_VERSION "3.4.0")
    if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.24.0")
        cmake_policy(SET CMP0135 NEW)
    endif()    
    FetchContent_Declare(Eigen3 URL "https://gitlab.com/libeigen/eigen/-/archive/${TARGET_EIGEN_VERSION}/eigen-${TARGET_EIGEN_VERSION}.tar.gz")
    FetchContent_Populate(Eigen3)
    SET(EIGEN3_INCLUDE_DIR "${eigen3_SOURCE_DIR}")
endif()

include_directories(${EIGEN3_INCLUDE_DIR})
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../include")
add_library(CppIndMach012_AltDSS SHARED CppIndMach012.cpp)
add_library(CppIndMach012_OpenDSSv7 SHARED CppIndMach012.cpp)
add_library(CppIndMach012_OpenDSSv8v9 SHARED CppIndMach012.cpp)
add_library(CppIndMach012_OpenDSSv10 SHARED CppIndMach012.cpp)

if(MSVC)
    # We don't need .EXP files, clutter...
    set(CMAKE_SHARED_LINKER_FLAGS "/NOEXP")
endif()

add_definitions(-DALTDSS_CAPI_DLL=) # Silence warnings, we won't use AltDSS/DSS C-API functions directly anyway.

target_compile_definitions(CppIndMach012_AltDSS PUBLIC ALTDSS_USERMODEL)
target_compile_definitions(CppIndMach012_OpenDSSv7 PUBLIC OPENDSS_USERMODEL_V7)
target_compile_definitions(CppIndMach012_OpenDSSv8v9 PUBLIC)
target_compile_definitions(CppIndMach012_OpenDSSv10 PUBLIC OPENDSS_USERMODEL_V10)

#TODO: share this across all projects, or just remove the manual stuff when we fully move from Free Pascal
if((CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64") OR (CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64"))
    SET(DSS_EXTENSIONS_OUT_DIR_SUFFIX "arm64")
elseif(NOT ${IS_ARM_PROCESSOR} EQUAL -1)
    SET(DSS_EXTENSIONS_OUT_DIR_SUFFIX "arm32")
elseif ("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
    SET(DSS_EXTENSIONS_OUT_DIR_SUFFIX "x64")
else ()
    SET(DSS_EXTENSIONS_OUT_DIR_SUFFIX "x86")
endif()
if ("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
    SET(DSS_EXTENSIONS_OUT_DIR_PREFIX "win")
elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Darwin")
    SET(DSS_EXTENSIONS_OUT_DIR_PREFIX "darwin")
elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    SET(DSS_EXTENSIONS_OUT_DIR_PREFIX "linux")
else ()
    MESSAGE(FATAL_ERROR "Unsupported system? ${CMAKE_SYSTEM_NAME}" )
endif()

if (DSS_EXTENSIONS)
    SET(DSS_EXTENSIONS_OUT_DIR "${CMAKE_SOURCE_DIR}/lib/${DSS_EXTENSIONS_OUT_DIR_PREFIX}_${DSS_EXTENSIONS_OUT_DIR_SUFFIX}")
    foreach(_tgt CppIndMach012_AltDSS CppIndMach012_OpenDSSv7 CppIndMach012_OpenDSSv8v9 CppIndMach012_OpenDSSv10)
        message(STATUS ${_tgt})
        set_target_properties(${_tgt} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${DSS_EXTENSIONS_OUT_DIR})
        set_target_properties(${_tgt} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY ${DSS_EXTENSIONS_OUT_DIR})
        set_target_properties(${_tgt} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${DSS_EXTENSIONS_OUT_DIR})
        set_target_properties(${_tgt} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY $<1:${DSS_EXTENSIONS_OUT_DIR}>)
        set_target_properties(${_tgt} PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${DSS_EXTENSIONS_OUT_DIR}>)
        set_target_properties(${_tgt} PROPERTIES RUNTIME_OUTPUT_DIRECTORY $<1:${DSS_EXTENSIONS_OUT_DIR}>)
    endforeach()
endif()
