namespace dss { namespace obj { namespace enums {

struct ClassIndices {
    enum {
        LineCode = 1,
        LoadShape = 2,
        TShape = 3,
        PriceShape = 4,
        XYcurve = 5,
        GrowthShape = 6,
        TCC_Curve = 7,
        Spectrum = 8,
        WireData = 9,
        CNData = 10,
        TSData = 11,
        LineSpacing = 12,
        LineGeometry = 13,
        XfmrCode = 14,
        Line = 15,
        Vsource = 16,
        Isource = 17,
        VCCS = 18,
        Load = 19,
        Transformer = 20,
        RegControl = 21,
        Capacitor = 22,
        Reactor = 23,
        CapControl = 24,
        Fault = 25,
        DynamicExp = 26,
        Generator = 27,
        WindGen = 28,
        GenDispatcher = 29,
        Storage = 30,
        StorageController = 31,
        Relay = 32,
        Recloser = 33,
        Fuse = 34,
        SwtControl = 35,
        PVSystem = 36,
        UPFC = 37,
        UPFCControl = 38,
        ESPVLControl = 39,
        IndMach012 = 40,
        GICsource = 41,
        AutoTrans = 42,
        InvControl = 43,
        ExpControl = 44,
        GICLine = 45,
        GICTransformer = 46,
        VSConverter = 47,
        Monitor = 48,
        EnergyMeter = 49,
        Sensor = 50,
        FMonitor = 51,
        Generic5 = 52,
    };
};

namespace properties {
    struct LineCode
    {
        enum {
            nphases = 1,
            r1 = 2,
            x1 = 3,
            r0 = 4,
            x0 = 5,
            C1 = 6,
            C0 = 7,
            units = 8,
            rmatrix = 9,
            xmatrix = 10,
            cmatrix = 11,
            baseFreq = 12,
            normamps = 13,
            emergamps = 14,
            faultrate = 15,
            pctperm = 16,
            repair = 17,
            Kron = 18,
            Rg = 19,
            Xg = 20,
            rho = 21,
            neutral = 22,
            B1 = 23,
            B0 = 24,
            Seasons = 25,
            Ratings = 26,
            LineType = 27,
            like = 28,
        };
    };

    struct LoadShape
    {
        enum {
            npts = 1,
            interval = 2,
            mult = 3,
            hour = 4,
            mean = 5,
            stddev = 6,
            csvfile = 7,
            sngfile = 8,
            dblfile = 9,
            action = 10,
            qmult = 11,
            UseActual = 12,
            Pmax = 13,
            Qmax = 14,
            sinterval = 15,
            minterval = 16,
            Pbase = 17,
            Qbase = 18,
            Pmult = 19,
            PQCSVFile = 20,
            MemoryMapping = 21,
            Interpolation = 22,
            like = 23,
        };
    };

    struct TShape
    {
        enum {
            npts = 1,
            interval = 2,
            temp = 3,
            hour = 4,
            mean = 5,
            stddev = 6,
            csvfile = 7,
            sngfile = 8,
            dblfile = 9,
            sinterval = 10,
            minterval = 11,
            action = 12,
            like = 13,
        };
    };

    struct PriceShape
    {
        enum {
            npts = 1,
            interval = 2,
            price = 3,
            hour = 4,
            mean = 5,
            stddev = 6,
            csvfile = 7,
            sngfile = 8,
            dblfile = 9,
            sinterval = 10,
            minterval = 11,
            action = 12,
            like = 13,
        };
    };

    struct XYcurve
    {
        enum {
            npts = 1,
            Points = 2,
            Yarray = 3,
            Xarray = 4,
            csvfile = 5,
            sngfile = 6,
            dblfile = 7,
            x = 8,
            y = 9,
            Xshift = 10,
            Yshift = 11,
            Xscale = 12,
            Yscale = 13,
            like = 14,
        };
    };

    struct GrowthShape
    {
        enum {
            npts = 1,
            year = 2,
            mult = 3,
            csvfile = 4,
            sngfile = 5,
            dblfile = 6,
            like = 7,
        };
    };

    struct TCC_Curve
    {
        enum {
            npts = 1,
            C_array = 2,
            T_array = 3,
            like = 4,
        };
    };

    struct Spectrum
    {
        enum {
            NumHarm = 1,
            harmonic = 2,
            pctmag = 3,
            angle = 4,
            CSVFile = 5,
            like = 6,
        };
    };

    struct WireData
    {
        enum {
            Rdc = 1,
            Rac = 2,
            Runits = 3,
            GMRac = 4,
            GMRunits = 5,
            radius = 6,
            radunits = 7,
            normamps = 8,
            emergamps = 9,
            diam = 10,
            Seasons = 11,
            Ratings = 12,
            Capradius = 13,
            like = 14,
        };
    };

    struct CNData
    {
        enum {
            k = 1,
            DiaStrand = 2,
            GmrStrand = 3,
            Rstrand = 4,
            EpsR = 5,
            InsLayer = 6,
            DiaIns = 7,
            DiaCable = 8,
            Rdc = 9,
            Rac = 10,
            Runits = 11,
            GMRac = 12,
            GMRunits = 13,
            radius = 14,
            radunits = 15,
            normamps = 16,
            emergamps = 17,
            diam = 18,
            Seasons = 19,
            Ratings = 20,
            Capradius = 21,
            like = 22,
        };
    };

    struct TSData
    {
        enum {
            DiaShield = 1,
            TapeLayer = 2,
            TapeLap = 3,
            EpsR = 4,
            InsLayer = 5,
            DiaIns = 6,
            DiaCable = 7,
            Rdc = 8,
            Rac = 9,
            Runits = 10,
            GMRac = 11,
            GMRunits = 12,
            radius = 13,
            radunits = 14,
            normamps = 15,
            emergamps = 16,
            diam = 17,
            Seasons = 18,
            Ratings = 19,
            Capradius = 20,
            like = 21,
        };
    };

    struct LineSpacing
    {
        enum {
            nconds = 1,
            nphases = 2,
            x = 3,
            h = 4,
            units = 5,
            like = 6,
        };
    };

    struct LineGeometry
    {
        enum {
            nconds = 1,
            nphases = 2,
            cond = 3,
            wire = 4,
            x = 5,
            h = 6,
            units = 7,
            normamps = 8,
            emergamps = 9,
            reduce = 10,
            spacing = 11,
            wires = 12,
            cncable = 13,
            tscable = 14,
            cncables = 15,
            tscables = 16,
            Seasons = 17,
            Ratings = 18,
            LineType = 19,
            like = 20,
        };
    };

    struct XfmrCode
    {
        enum {
            phases = 1,
            windings = 2,
            wdg = 3,
            conn = 4,
            kV = 5,
            kVA = 6,
            tap = 7,
            pctR = 8,
            Rneut = 9,
            Xneut = 10,
            conns = 11,
            kVs = 12,
            kVAs = 13,
            taps = 14,
            Xhl = 15,
            Xht = 16,
            Xlt = 17,
            Xscarray = 18,
            thermal = 19,
            n = 20,
            m = 21,
            flrise = 22,
            hsrise = 23,
            pctloadloss = 24,
            pctnoloadloss = 25,
            normhkVA = 26,
            emerghkVA = 27,
            MaxTap = 28,
            MinTap = 29,
            NumTaps = 30,
            pctimag = 31,
            ppm_antifloat = 32,
            pctRs = 33,
            X12 = 34,
            X13 = 35,
            X23 = 36,
            RdcOhms = 37,
            Seasons = 38,
            Ratings = 39,
            like = 40,
        };
    };

    struct Line
    {
        enum {
            bus1 = 1,
            bus2 = 2,
            linecode = 3,
            length = 4,
            phases = 5,
            r1 = 6,
            x1 = 7,
            r0 = 8,
            x0 = 9,
            C1 = 10,
            C0 = 11,
            rmatrix = 12,
            xmatrix = 13,
            cmatrix = 14,
            Switch = 15,
            Rg = 16,
            Xg = 17,
            rho = 18,
            geometry = 19,
            units = 20,
            spacing = 21,
            wires = 22,
            EarthModel = 23,
            cncables = 24,
            tscables = 25,
            B1 = 26,
            B0 = 27,
            Seasons = 28,
            Ratings = 29,
            LineType = 30,
            normamps = 31,
            emergamps = 32,
            faultrate = 33,
            pctperm = 34,
            repair = 35,
            basefreq = 36,
            enabled = 37,
            like = 38,
        };
    };

    struct Vsource
    {
        enum {
            bus1 = 1,
            basekv = 2,
            pu = 3,
            angle = 4,
            frequency = 5,
            phases = 6,
            MVAsc3 = 7,
            MVAsc1 = 8,
            x1r1 = 9,
            x0r0 = 10,
            Isc3 = 11,
            Isc1 = 12,
            R1 = 13,
            X1 = 14,
            R0 = 15,
            X0 = 16,
            ScanType = 17,
            Sequence = 18,
            bus2 = 19,
            Z1 = 20,
            Z0 = 21,
            Z2 = 22,
            puZ1 = 23,
            puZ0 = 24,
            puZ2 = 25,
            baseMVA = 26,
            Yearly = 27,
            Daily = 28,
            Duty = 29,
            Model = 30,
            puZideal = 31,
            spectrum = 32,
            basefreq = 33,
            enabled = 34,
            like = 35,
        };
    };

    struct Isource
    {
        enum {
            bus1 = 1,
            amps = 2,
            angle = 3,
            frequency = 4,
            phases = 5,
            scantype = 6,
            sequence = 7,
            Yearly = 8,
            Daily = 9,
            Duty = 10,
            Bus2 = 11,
            spectrum = 12,
            basefreq = 13,
            enabled = 14,
            like = 15,
        };
    };

    struct VCCS
    {
        enum {
            bus1 = 1,
            phases = 2,
            prated = 3,
            vrated = 4,
            ppct = 5,
            bp1 = 6,
            bp2 = 7,
            filter = 8,
            fsample = 9,
            rmsmode = 10,
            imaxpu = 11,
            vrmstau = 12,
            irmstau = 13,
            spectrum = 14,
            basefreq = 15,
            enabled = 16,
            like = 17,
        };
    };

    struct Load
    {
        enum {
            phases = 1,
            bus1 = 2,
            kV = 3,
            kW = 4,
            pf = 5,
            model = 6,
            yearly = 7,
            daily = 8,
            duty = 9,
            growth = 10,
            conn = 11,
            kvar = 12,
            Rneut = 13,
            Xneut = 14,
            status = 15,
            cls = 16,
            Vminpu = 17,
            Vmaxpu = 18,
            Vminnorm = 19,
            Vminemerg = 20,
            xfkVA = 21,
            allocationfactor = 22,
            kVA = 23,
            pctmean = 24,
            pctstddev = 25,
            CVRwatts = 26,
            CVRvars = 27,
            kwh = 28,
            kwhdays = 29,
            Cfactor = 30,
            CVRcurve = 31,
            NumCust = 32,
            ZIPV = 33,
            pctSeriesRL = 34,
            RelWeight = 35,
            Vlowpu = 36,
            puXharm = 37,
            XRharm = 38,
            spectrum = 39,
            basefreq = 40,
            enabled = 41,
            like = 42,
        };
    };

    struct Transformer
    {
        enum {
            phases = 1,
            windings = 2,
            wdg = 3,
            bus = 4,
            conn = 5,
            kV = 6,
            kVA = 7,
            tap = 8,
            pctR = 9,
            Rneut = 10,
            Xneut = 11,
            buses = 12,
            conns = 13,
            kVs = 14,
            kVAs = 15,
            taps = 16,
            XHL = 17,
            XHT = 18,
            XLT = 19,
            Xscarray = 20,
            thermal = 21,
            n = 22,
            m = 23,
            flrise = 24,
            hsrise = 25,
            pctloadloss = 26,
            pctnoloadloss = 27,
            normhkVA = 28,
            emerghkVA = 29,
            sub = 30,
            MaxTap = 31,
            MinTap = 32,
            NumTaps = 33,
            subname = 34,
            pctimag = 35,
            ppm_antifloat = 36,
            pctRs = 37,
            bank = 38,
            XfmrCode = 39,
            XRConst = 40,
            X12 = 41,
            X13 = 42,
            X23 = 43,
            LeadLag = 44,
            WdgCurrents = 45,
            Core = 46,
            RdcOhms = 47,
            Seasons = 48,
            Ratings = 49,
            normamps = 50,
            emergamps = 51,
            faultrate = 52,
            pctperm = 53,
            repair = 54,
            basefreq = 55,
            enabled = 56,
            like = 57,
        };
    };

    struct Capacitor
    {
        enum {
            bus1 = 1,
            bus2 = 2,
            phases = 3,
            kvar = 4,
            kv = 5,
            conn = 6,
            cmatrix = 7,
            cuf = 8,
            R = 9,
            XL = 10,
            Harm = 11,
            Numsteps = 12,
            states = 13,
            normamps = 14,
            emergamps = 15,
            faultrate = 16,
            pctperm = 17,
            repair = 18,
            basefreq = 19,
            enabled = 20,
            like = 21,
        };
    };

    struct Reactor
    {
        enum {
            bus1 = 1,
            bus2 = 2,
            phases = 3,
            kvar = 4,
            kv = 5,
            conn = 6,
            Rmatrix = 7,
            Xmatrix = 8,
            Parallel = 9,
            R = 10,
            X = 11,
            Rp = 12,
            Z1 = 13,
            Z2 = 14,
            Z0 = 15,
            Z = 16,
            RCurve = 17,
            LCurve = 18,
            LmH = 19,
            normamps = 20,
            emergamps = 21,
            faultrate = 22,
            pctperm = 23,
            repair = 24,
            basefreq = 25,
            enabled = 26,
            like = 27,
        };
    };

    struct CapControl
    {
        enum {
            element = 1,
            terminal = 2,
            capacitor = 3,
            type = 4,
            PTratio = 5,
            CTratio = 6,
            ONsetting = 7,
            OFFsetting = 8,
            Delay = 9,
            VoltOverride = 10,
            Vmax = 11,
            Vmin = 12,
            DelayOFF = 13,
            DeadTime = 14,
            CTPhase = 15,
            PTPhase = 16,
            VBus = 17,
            EventLog = 18,
            UserModel = 19,
            UserData = 20,
            pctMinkvar = 21,
            Reset = 22,
            ControlSignal = 23,
            basefreq = 24,
            enabled = 25,
            like = 26,
        };
    };

    struct Fault
    {
        enum {
            bus1 = 1,
            bus2 = 2,
            phases = 3,
            r = 4,
            pctstddev = 5,
            Gmatrix = 6,
            ONtime = 7,
            temporary = 8,
            MinAmps = 9,
            normamps = 10,
            emergamps = 11,
            faultrate = 12,
            pctperm = 13,
            repair = 14,
            basefreq = 15,
            enabled = 16,
            like = 17,
        };
    };

    struct DynamicExp
    {
        enum {
            NVariables = 1,
            VarNames = 2,
            var = 3,
            VarIdx = 4,
            Expression = 5,
            Domain = 6,
            like = 7,
        };
    };

    struct Generator
    {
        enum {
            phases = 1,
            bus1 = 2,
            kv = 3,
            kW = 4,
            pf = 5,
            kvar = 6,
            model = 7,
            Vminpu = 8,
            Vmaxpu = 9,
            yearly = 10,
            daily = 11,
            duty = 12,
            dispmode = 13,
            dispvalue = 14,
            conn = 15,
            status = 16,
            cls = 17,
            Vpu = 18,
            maxkvar = 19,
            minkvar = 20,
            pvfactor = 21,
            forceon = 22,
            kVA = 23,
            MVA = 24,
            Xd = 25,
            Xdp = 26,
            Xdpp = 27,
            H = 28,
            D = 29,
            UserModel = 30,
            UserData = 31,
            ShaftModel = 32,
            ShaftData = 33,
            DutyStart = 34,
            debugtrace = 35,
            Balanced = 36,
            XRdp = 37,
            UseFuel = 38,
            FuelkWh = 39,
            pctFuel = 40,
            pctReserve = 41,
            Refuel = 42,
            DynamicEq = 43,
            DynOut = 44,
            spectrum = 45,
            basefreq = 46,
            enabled = 47,
            like = 48,
        };
    };

    struct WindGen
    {
        enum {
            phases = 1,
            bus1 = 2,
            kv = 3,
            kW = 4,
            PF = 5,
            model = 6,
            yearly = 7,
            daily = 8,
            duty = 9,
            conn = 10,
            kvar = 11,
            cls = 12,
            debugtrace = 13,
            Vminpu = 14,
            Vmaxpu = 15,
            kVA = 16,
            MVA = 17,
            DutyStart = 18,
            DynamicEq = 19,
            DynOut = 20,
            Rthev = 21,
            Xthev = 22,
            Vss = 23,
            Pss = 24,
            Qss = 25,
            vwind = 26,
            QMode = 27,
            SimMechFlg = 28,
            APCFlg = 29,
            QFlg = 30,
            delt0 = 31,
            N_WTG = 32,
            VV_Curve = 33,
            Ag = 34,
            Cp = 35,
            Lamda = 36,
            P = 37,
            pd = 38,
            PLoss = 39,
            Rad = 40,
            VCutIn = 41,
            VCutOut = 42,
            spectrum = 43,
            basefreq = 44,
            enabled = 45,
            like = 46,
        };
    };

    struct GenDispatcher
    {
        enum {
            Element = 1,
            Terminal = 2,
            kWLimit = 3,
            kWBand = 4,
            kvarlimit = 5,
            GenList = 6,
            Weights = 7,
            basefreq = 8,
            enabled = 9,
            like = 10,
        };
    };

    struct Storage
    {
        enum {
            phases = 1,
            bus1 = 2,
            kv = 3,
            conn = 4,
            kW = 5,
            kvar = 6,
            pf = 7,
            kVA = 8,
            pctCutin = 9,
            pctCutout = 10,
            EffCurve = 11,
            VarFollowInverter = 12,
            kvarMax = 13,
            kvarMaxAbs = 14,
            WattPriority = 15,
            PFPriority = 16,
            pctPminNoVars = 17,
            pctPminkvarMax = 18,
            kWrated = 19,
            pctkWrated = 20,
            kWhrated = 21,
            kWhstored = 22,
            pctstored = 23,
            pctreserve = 24,
            State = 25,
            pctDischarge = 26,
            pctCharge = 27,
            pctEffCharge = 28,
            pctEffDischarge = 29,
            pctIdlingkW = 30,
            pctIdlingkvar = 31,
            pctR = 32,
            pctX = 33,
            model = 34,
            Vminpu = 35,
            Vmaxpu = 36,
            Balanced = 37,
            LimitCurrent = 38,
            yearly = 39,
            daily = 40,
            duty = 41,
            DispMode = 42,
            DischargeTrigger = 43,
            ChargeTrigger = 44,
            TimeChargeTrig = 45,
            cls = 46,
            DynaDLL = 47,
            DynaData = 48,
            UserModel = 49,
            UserData = 50,
            debugtrace = 51,
            kVDC = 52,
            Kp = 53,
            PITol = 54,
            SafeVoltage = 55,
            SafeMode = 56,
            DynamicEq = 57,
            DynOut = 58,
            ControlMode = 59,
            AmpLimit = 60,
            AmpLimitGain = 61,
            spectrum = 62,
            basefreq = 63,
            enabled = 64,
            like = 65,
        };
    };

    struct StorageController
    {
        enum {
            Element = 1,
            Terminal = 2,
            MonPhase = 3,
            kWTarget = 4,
            kWTargetLow = 5,
            pctkWBand = 6,
            kWBand = 7,
            pctkWBandLow = 8,
            kWBandLow = 9,
            ElementList = 10,
            Weights = 11,
            ModeDischarge = 12,
            ModeCharge = 13,
            TimeDischargeTrigger = 14,
            TimeChargeTrigger = 15,
            pctRatekW = 16,
            pctRateCharge = 17,
            pctReserve = 18,
            kWhTotal = 19,
            kWTotal = 20,
            kWhActual = 21,
            kWActual = 22,
            kWneed = 23,
            Yearly = 24,
            Daily = 25,
            Duty = 26,
            EventLog = 27,
            InhibitTime = 28,
            Tup = 29,
            TFlat = 30,
            Tdn = 31,
            kWThreshold = 32,
            DispFactor = 33,
            ResetLevel = 34,
            Seasons = 35,
            SeasonTargets = 36,
            SeasonTargetsLow = 37,
            basefreq = 38,
            enabled = 39,
            like = 40,
        };
    };

    struct Relay
    {
        enum {
            MonitoredObj = 1,
            MonitoredTerm = 2,
            SwitchedObj = 3,
            SwitchedTerm = 4,
            type = 5,
            Phasecurve = 6,
            Groundcurve = 7,
            PhaseTrip = 8,
            GroundTrip = 9,
            TDPhase = 10,
            TDGround = 11,
            PhaseInst = 12,
            GroundInst = 13,
            Reset = 14,
            Shots = 15,
            RecloseIntervals = 16,
            Delay = 17,
            Overvoltcurve = 18,
            Undervoltcurve = 19,
            kvbase = 20,
            pctPickup47 = 21,
            BaseAmps46 = 22,
            pctPickup46 = 23,
            isqt46 = 24,
            Variable = 25,
            overtrip = 26,
            undertrip = 27,
            Breakertime = 28,
            action = 29,
            Z1mag = 30,
            Z1ang = 31,
            Z0mag = 32,
            Z0ang = 33,
            Mphase = 34,
            Mground = 35,
            EventLog = 36,
            DebugTrace = 37,
            DistReverse = 38,
            Normal = 39,
            State = 40,
            DOC_TiltAngleLow = 41,
            DOC_TiltAngleHigh = 42,
            DOC_TripSettingLow = 43,
            DOC_TripSettingHigh = 44,
            DOC_TripSettingMag = 45,
            DOC_DelayInner = 46,
            DOC_PhaseCurveInner = 47,
            DOC_PhaseTripInner = 48,
            DOC_TDPhaseInner = 49,
            DOC_P1Blocking = 50,
            basefreq = 51,
            enabled = 52,
            like = 53,
        };
    };

    struct Recloser
    {
        enum {
            MonitoredObj = 1,
            MonitoredTerm = 2,
            SwitchedObj = 3,
            SwitchedTerm = 4,
            NumFast = 5,
            PhaseFast = 6,
            PhaseDelayed = 7,
            GroundFast = 8,
            GroundDelayed = 9,
            PhaseTrip = 10,
            GroundTrip = 11,
            PhaseInst = 12,
            GroundInst = 13,
            Reset = 14,
            Shots = 15,
            RecloseIntervals = 16,
            Delay = 17,
            Action = 18,
            TDPhFast = 19,
            TDGrFast = 20,
            TDPhDelayed = 21,
            TDGrDelayed = 22,
            Normal = 23,
            State = 24,
            basefreq = 25,
            enabled = 26,
            like = 27,
        };
    };

    struct Fuse
    {
        enum {
            MonitoredObj = 1,
            MonitoredTerm = 2,
            SwitchedObj = 3,
            SwitchedTerm = 4,
            FuseCurve = 5,
            RatedCurrent = 6,
            Delay = 7,
            Action = 8,
            Normal = 9,
            State = 10,
            basefreq = 11,
            enabled = 12,
            like = 13,
        };
    };

    struct SwtControl
    {
        enum {
            SwitchedObj = 1,
            SwitchedTerm = 2,
            Action = 3,
            Lock = 4,
            Delay = 5,
            Normal = 6,
            State = 7,
            Reset = 8,
            basefreq = 9,
            enabled = 10,
            like = 11,
        };
    };

    struct PVSystem
    {
        enum {
            phases = 1,
            bus1 = 2,
            kv = 3,
            irradiance = 4,
            Pmpp = 5,
            pctPmpp = 6,
            Temperature = 7,
            pf = 8,
            conn = 9,
            kvar = 10,
            kVA = 11,
            pctCutin = 12,
            pctCutout = 13,
            EffCurve = 14,
            PTCurve = 15,
            pctR = 16,
            pctX = 17,
            model = 18,
            Vminpu = 19,
            Vmaxpu = 20,
            Balanced = 21,
            LimitCurrent = 22,
            yearly = 23,
            daily = 24,
            duty = 25,
            Tyearly = 26,
            Tdaily = 27,
            Tduty = 28,
            cls = 29,
            UserModel = 30,
            UserData = 31,
            debugtrace = 32,
            VarFollowInverter = 33,
            DutyStart = 34,
            WattPriority = 35,
            PFPriority = 36,
            pctPminNoVars = 37,
            pctPminkvarMax = 38,
            kvarMax = 39,
            kvarMaxAbs = 40,
            kVDC = 41,
            Kp = 42,
            PITol = 43,
            SafeVoltage = 44,
            SafeMode = 45,
            DynamicEq = 46,
            DynOut = 47,
            ControlMode = 48,
            AmpLimit = 49,
            AmpLimitGain = 50,
            spectrum = 51,
            basefreq = 52,
            enabled = 53,
            like = 54,
        };
    };

    struct UPFC
    {
        enum {
            bus1 = 1,
            bus2 = 2,
            refkv = 3,
            pf = 4,
            frequency = 5,
            phases = 6,
            Xs = 7,
            Tol1 = 8,
            Mode = 9,
            VpqMax = 10,
            LossCurve = 11,
            VHLimit = 12,
            VLLimit = 13,
            CLimit = 14,
            refkv2 = 15,
            kvarLimit = 16,
            Element = 17,
            spectrum = 18,
            basefreq = 19,
            enabled = 20,
            like = 21,
        };
    };

    struct UPFCControl
    {
        enum {
            UPFCList = 1,
            basefreq = 2,
            enabled = 3,
            like = 4,
        };
    };

    struct ESPVLControl
    {
        enum {
            Element = 1,
            Terminal = 2,
            Type = 3,
            kWBand = 4,
            kvarlimit = 5,
            LocalControlList = 6,
            LocalControlWeights = 7,
            PVSystemList = 8,
            PVSystemWeights = 9,
            StorageList = 10,
            StorageWeights = 11,
            basefreq = 12,
            enabled = 13,
            like = 14,
        };
    };

    struct IndMach012
    {
        enum {
            phases = 1,
            bus1 = 2,
            kv = 3,
            kW = 4,
            pf = 5,
            conn = 6,
            kVA = 7,
            H = 8,
            D = 9,
            puRs = 10,
            puXs = 11,
            puRr = 12,
            puXr = 13,
            puXm = 14,
            Slip = 15,
            MaxSlip = 16,
            SlipOption = 17,
            Yearly = 18,
            Daily = 19,
            Duty = 20,
            Debugtrace = 21,
            spectrum = 22,
            basefreq = 23,
            enabled = 24,
            like = 25,
        };
    };

    struct GICsource
    {
        enum {
            Volts = 1,
            angle = 2,
            frequency = 3,
            phases = 4,
            EN = 5,
            EE = 6,
            Lat1 = 7,
            Lon1 = 8,
            Lat2 = 9,
            Lon2 = 10,
            spectrum = 11,
            basefreq = 12,
            enabled = 13,
            like = 14,
        };
    };

    struct AutoTrans
    {
        enum {
            phases = 1,
            windings = 2,
            wdg = 3,
            bus = 4,
            conn = 5,
            kV = 6,
            kVA = 7,
            tap = 8,
            pctR = 9,
            Rdcohms = 10,
            Core = 11,
            buses = 12,
            conns = 13,
            kVs = 14,
            kVAs = 15,
            taps = 16,
            XHX = 17,
            XHT = 18,
            XXT = 19,
            XSCarray = 20,
            thermal = 21,
            n = 22,
            m = 23,
            flrise = 24,
            hsrise = 25,
            pctloadloss = 26,
            pctnoloadloss = 27,
            normhkVA = 28,
            emerghkVA = 29,
            sub = 30,
            MaxTap = 31,
            MinTap = 32,
            NumTaps = 33,
            subname = 34,
            pctimag = 35,
            ppm_antifloat = 36,
            pctRs = 37,
            bank = 38,
            XRConst = 39,
            LeadLag = 40,
            WdgCurrents = 41,
            normamps = 42,
            emergamps = 43,
            faultrate = 44,
            pctperm = 45,
            repair = 46,
            basefreq = 47,
            enabled = 48,
            like = 49,
        };
    };

    struct RegControl
    {
        enum {
            transformer = 1,
            winding = 2,
            vreg = 3,
            band = 4,
            ptratio = 5,
            CTprim = 6,
            R = 7,
            X = 8,
            bus = 9,
            delay = 10,
            reversible = 11,
            revvreg = 12,
            revband = 13,
            revR = 14,
            revX = 15,
            tapdelay = 16,
            debugtrace = 17,
            maxtapchange = 18,
            inversetime = 19,
            tapwinding = 20,
            vlimit = 21,
            PTphase = 22,
            revThreshold = 23,
            revDelay = 24,
            revNeutral = 25,
            EventLog = 26,
            RemotePTRatio = 27,
            TapNum = 28,
            Reset = 29,
            LDC_Z = 30,
            rev_Z = 31,
            Cogen = 32,
            basefreq = 33,
            enabled = 34,
            like = 35,
        };
    };

    struct InvControl
    {
        enum {
            DERList = 1,
            Mode = 2,
            CombiMode = 3,
            vvc_curve1 = 4,
            hysteresis_offset = 5,
            voltage_curvex_ref = 6,
            avgwindowlen = 7,
            voltwatt_curve = 8,
            DbVMin = 9,
            DbVMax = 10,
            ArGraLowV = 11,
            ArGraHiV = 12,
            DynReacavgwindowlen = 13,
            deltaQ_Factor = 14,
            VoltageChangeTolerance = 15,
            VarChangeTolerance = 16,
            VoltwattYAxis = 17,
            RateofChangeMode = 18,
            LPFTau = 19,
            RiseFallLimit = 20,
            deltaP_Factor = 21,
            EventLog = 22,
            RefReactivePower = 23,
            ActivePChangeTolerance = 24,
            monVoltageCalc = 25,
            monBus = 26,
            MonBusesVbase = 27,
            voltwattCH_curve = 28,
            wattpf_curve = 29,
            wattvar_curve = 30,
            VV_RefReactivePower = 31,
            PVSystemList = 32,
            Vsetpoint = 33,
            ControlModel = 34,
            basefreq = 35,
            enabled = 36,
            like = 37,
        };
    };

    struct ExpControl
    {
        enum {
            PVSystemList = 1,
            Vreg = 2,
            Slope = 3,
            VregTau = 4,
            Qbias = 5,
            VregMin = 6,
            VregMax = 7,
            QmaxLead = 8,
            QmaxLag = 9,
            EventLog = 10,
            DeltaQ_factor = 11,
            PreferQ = 12,
            Tresponse = 13,
            DERList = 14,
            basefreq = 15,
            enabled = 16,
            like = 17,
        };
    };

    struct GICLine
    {
        enum {
            bus1 = 1,
            bus2 = 2,
            Volts = 3,
            Angle = 4,
            frequency = 5,
            phases = 6,
            R = 7,
            X = 8,
            C = 9,
            EN = 10,
            EE = 11,
            Lat1 = 12,
            Lon1 = 13,
            Lat2 = 14,
            Lon2 = 15,
            spectrum = 16,
            basefreq = 17,
            enabled = 18,
            like = 19,
        };
    };

    struct GICTransformer
    {
        enum {
            BusH = 1,
            BusNH = 2,
            BusX = 3,
            BusNX = 4,
            phases = 5,
            Type = 6,
            R1 = 7,
            R2 = 8,
            KVLL1 = 9,
            KVLL2 = 10,
            MVA = 11,
            VarCurve = 12,
            pctR1 = 13,
            pctR2 = 14,
            K = 15,
            normamps = 16,
            emergamps = 17,
            faultrate = 18,
            pctperm = 19,
            repair = 20,
            basefreq = 21,
            enabled = 22,
            like = 23,
        };
    };

    struct VSConverter
    {
        enum {
            phases = 1,
            Bus1 = 2,
            kVac = 3,
            kVdc = 4,
            kW = 5,
            Ndc = 6,
            Rac = 7,
            Xac = 8,
            m0 = 9,
            d0 = 10,
            Mmin = 11,
            Mmax = 12,
            Iacmax = 13,
            Idcmax = 14,
            Vacref = 15,
            Pacref = 16,
            Qacref = 17,
            Vdcref = 18,
            VscMode = 19,
            spectrum = 20,
            basefreq = 21,
            enabled = 22,
            like = 23,
        };
    };

    struct Monitor
    {
        enum {
            element = 1,
            terminal = 2,
            mode = 3,
            action = 4,
            residual = 5,
            VIPolar = 6,
            PPolar = 7,
            basefreq = 8,
            enabled = 9,
            like = 10,
        };
    };

    struct EnergyMeter
    {
        enum {
            element = 1,
            terminal = 2,
            action = 3,
            option = 4,
            kVAnormal = 5,
            kVAemerg = 6,
            peakcurrent = 7,
            Zonelist = 8,
            LocalOnly = 9,
            Mask = 10,
            Losses = 11,
            LineLosses = 12,
            XfmrLosses = 13,
            SeqLosses = 14,
            ThreePhaseLosses = 15,
            VbaseLosses = 16,
            PhaseVoltageReport = 17,
            Int_Rate = 18,
            Int_Duration = 19,
            SAIFI = 20,
            SAIFIkW = 21,
            SAIDI = 22,
            CAIDI = 23,
            CustInterrupts = 24,
            basefreq = 25,
            enabled = 26,
            like = 27,
        };
    };

    struct Sensor
    {
        enum {
            element = 1,
            terminal = 2,
            kvbase = 3,
            clear = 4,
            kVs = 5,
            currents = 6,
            kWs = 7,
            kvars = 8,
            conn = 9,
            Deltadirection = 10,
            pctError = 11,
            Weight = 12,
            basefreq = 13,
            enabled = 14,
            like = 15,
        };
    };

    struct FMonitor
    {
        enum {
        };
    };

    struct Generic5
    {
        enum {
            phases = 1,
            bus1 = 2,
            kv = 3,
            kW = 4,
            pf = 5,
            conn = 6,
            kVA = 7,
            H = 8,
            D = 9,
            P_ref1kW = 10,
            P_ref2kW = 11,
            P_ref3kW = 12,
            V_ref1kVLN = 13,
            V_ref2kVLN = 14,
            V_ref3kVLN = 15,
            MaxSlip = 16,
            SlipOption = 17,
            Yearly = 18,
            Daily = 19,
            Duty = 20,
            Debugtrace = 21,
            P_refkW = 22,
            Q_refkVAr = 23,
            Cluster_num = 24,
            V_refkVLN = 25,
            ctrl_mode = 26,
            QV_flag = 27,
            kcd = 28,
            kcq = 29,
            kqi = 30,
            Q_ref1kVAr = 31,
            Q_ref2kVAr = 32,
            Q_ref3kVAr = 33,
            PmaxkW = 34,
            PminkW = 35,
            PQpriority = 36,
            PmppkW = 37,
            Pfctr1 = 38,
            Pfctr2 = 39,
            Pfctr3 = 40,
            Pfctr4 = 41,
            Pfctr5 = 42,
            Pfctr6 = 43,
            PbiaskW = 44,
            CC_Switch = 45,
            kcq_drp2 = 46,
            Volt_Trhd = 47,
            droop = 48,
            spectrum = 49,
            basefreq = 50,
            enabled = 51,
            like = 52,
        };
    };

} // namespace properties
} } } // namespace dss::obj::enums

