#ifndef DSSPM_CAPI_DLL_H
#define DSSPM_CAPI_DLL_H
#define DSSPM_CAPI_VERSION "0.9.2"
#ifndef DSSPM_CAPI_DLL
//#define DSSPM_CAPI_DLL __declspec(dllimport)
#define DSSPM_CAPI_DLL
#endif
#ifdef __cplusplus
extern "C" {
#else
#endif
    DSSPM_CAPI_DLL void DSS_ResetStringBuffer(void);
    DSSPM_CAPI_DLL void DSS_Dispose_PByte(int8_t** p);
    DSSPM_CAPI_DLL void DSS_Dispose_PDouble(double** p);
    DSSPM_CAPI_DLL void DSS_Dispose_PInteger(int32_t** p);
    DSSPM_CAPI_DLL void DSS_Dispose_PPAnsiChar(char ***p, int32_t cnt);

    DSS_CAPI_DLL void ActiveClass_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t ActiveClass_Get_First(void);
    DSS_CAPI_DLL int32_t ActiveClass_Get_Next(void);
    DSS_CAPI_DLL char* ActiveClass_Get_Name(void);
    DSS_CAPI_DLL void ActiveClass_Set_Name(char* Value);
    DSS_CAPI_DLL int32_t ActiveClass_Get_NumElements(void);
    DSS_CAPI_DLL char* ActiveClass_Get_ActiveClassName(void);
    DSS_CAPI_DLL int32_t ActiveClass_Get_Count(void);
    DSS_CAPI_DLL char* Bus_Get_Name(void);
    DSS_CAPI_DLL int32_t Bus_Get_NumNodes(void);
    DSS_CAPI_DLL void Bus_Get_SeqVoltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_Voltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_Nodes(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_Isc(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_Voc(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Bus_Get_kVBase(void);
    DSS_CAPI_DLL void Bus_Get_puVoltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_Zsc0(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_Zsc1(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_ZscMatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL uint16_t Bus_ZscRefresh(void);
    DSS_CAPI_DLL void Bus_Get_YscMatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL uint16_t Bus_Get_Coorddefined(void);
    DSS_CAPI_DLL double Bus_Get_x(void);
    DSS_CAPI_DLL void Bus_Set_x(double Value);
    DSS_CAPI_DLL double Bus_Get_y(void);
    DSS_CAPI_DLL void Bus_Set_y(double Value);
    DSS_CAPI_DLL double Bus_Get_Distance(void);
    DSS_CAPI_DLL int32_t Bus_GetUniqueNodeNumber(int32_t StartNumber);
    DSS_CAPI_DLL void Bus_Get_CplxSeqVoltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Bus_Get_Int_Duration(void);
    DSS_CAPI_DLL double Bus_Get_Lambda(void);
    DSS_CAPI_DLL double Bus_Get_Cust_Duration(void);
    DSS_CAPI_DLL double Bus_Get_Cust_Interrupts(void);
    DSS_CAPI_DLL int32_t Bus_Get_N_Customers(void);
    DSS_CAPI_DLL double Bus_Get_N_interrupts(void);
    DSS_CAPI_DLL void Bus_Get_puVLL(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_VLL(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_puVmagAngle(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Bus_Get_VMagAngle(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Bus_Get_TotalMiles(void);
    DSS_CAPI_DLL int32_t Bus_Get_SectionID(void);
    DSS_CAPI_DLL void Capacitors_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Capacitors_Get_First(void);
    DSS_CAPI_DLL uint16_t Capacitors_Get_IsDelta(void);
    DSS_CAPI_DLL double Capacitors_Get_kV(void);
    DSS_CAPI_DLL double Capacitors_Get_kvar(void);
    DSS_CAPI_DLL char* Capacitors_Get_Name(void);
    DSS_CAPI_DLL int32_t Capacitors_Get_Next(void);
    DSS_CAPI_DLL int32_t Capacitors_Get_NumSteps(void);
    DSS_CAPI_DLL void Capacitors_Set_IsDelta(uint16_t Value);
    DSS_CAPI_DLL void Capacitors_Set_kV(double Value);
    DSS_CAPI_DLL void Capacitors_Set_kvar(double Value);
    DSS_CAPI_DLL void Capacitors_Set_Name(char* Value);
    DSS_CAPI_DLL void Capacitors_Set_NumSteps(int32_t Value);
    DSS_CAPI_DLL int32_t Capacitors_Get_Count(void);
    DSS_CAPI_DLL uint16_t Capacitors_AddStep(void);
    DSS_CAPI_DLL uint16_t Capacitors_SubtractStep(void);
    DSS_CAPI_DLL int32_t Capacitors_Get_AvailableSteps(void);
    DSS_CAPI_DLL void Capacitors_Get_States(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Capacitors_Set_States(int32_t* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Capacitors_Open(void);
    DSS_CAPI_DLL void Capacitors_Close(void);
    DSS_CAPI_DLL void CapControls_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* CapControls_Get_Capacitor(void);
    DSS_CAPI_DLL double CapControls_Get_CTratio(void);
    DSS_CAPI_DLL double CapControls_Get_DeadTime(void);
    DSS_CAPI_DLL double CapControls_Get_Delay(void);
    DSS_CAPI_DLL double CapControls_Get_DelayOff(void);
    DSS_CAPI_DLL int32_t CapControls_Get_First(void);
    DSS_CAPI_DLL int32_t CapControls_Get_Mode(void);
    DSS_CAPI_DLL char* CapControls_Get_MonitoredObj(void);
    DSS_CAPI_DLL int32_t CapControls_Get_MonitoredTerm(void);
    DSS_CAPI_DLL char* CapControls_Get_Name(void);
    DSS_CAPI_DLL int32_t CapControls_Get_Next(void);
    DSS_CAPI_DLL double CapControls_Get_OFFSetting(void);
    DSS_CAPI_DLL double CapControls_Get_ONSetting(void);
    DSS_CAPI_DLL double CapControls_Get_PTratio(void);
    DSS_CAPI_DLL uint16_t CapControls_Get_UseVoltOverride(void);
    DSS_CAPI_DLL double CapControls_Get_Vmax(void);
    DSS_CAPI_DLL double CapControls_Get_Vmin(void);
    DSS_CAPI_DLL void CapControls_Set_Capacitor(char* Value);
    DSS_CAPI_DLL void CapControls_Set_CTratio(double Value);
    DSS_CAPI_DLL void CapControls_Set_DeadTime(double Value);
    DSS_CAPI_DLL void CapControls_Set_Delay(double Value);
    DSS_CAPI_DLL void CapControls_Set_DelayOff(double Value);
    DSS_CAPI_DLL void CapControls_Set_Mode(int32_t Value);
    DSS_CAPI_DLL void CapControls_Set_MonitoredObj(char* Value);
    DSS_CAPI_DLL void CapControls_Set_MonitoredTerm(int32_t Value);
    DSS_CAPI_DLL void CapControls_Set_Name(char* Value);
    DSS_CAPI_DLL void CapControls_Set_OFFSetting(double Value);
    DSS_CAPI_DLL void CapControls_Set_ONSetting(double Value);
    DSS_CAPI_DLL void CapControls_Set_PTratio(double Value);
    DSS_CAPI_DLL void CapControls_Set_UseVoltOverride(uint16_t Value);
    DSS_CAPI_DLL void CapControls_Set_Vmax(double Value);
    DSS_CAPI_DLL void CapControls_Set_Vmin(double Value);
    DSS_CAPI_DLL int32_t CapControls_Get_Count(void);
    DSS_CAPI_DLL void CapControls_Reset(void);
    DSS_CAPI_DLL char* Circuit_Get_Name(void);
    DSS_CAPI_DLL int32_t Circuit_Get_NumBuses(void);
    DSS_CAPI_DLL int32_t Circuit_Get_NumCktElements(void);
    DSS_CAPI_DLL int32_t Circuit_Get_NumNodes(void);
    DSS_CAPI_DLL void Circuit_Get_LineLosses(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_Losses(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllBusVmag(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllBusVolts(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllElementNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_SubstationLosses(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_TotalPower(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Disable(char* Name);
    DSS_CAPI_DLL void Circuit_Enable(char* Name);
    DSS_CAPI_DLL int32_t Circuit_FirstPCElement(void);
    DSS_CAPI_DLL int32_t Circuit_FirstPDElement(void);
    DSS_CAPI_DLL int32_t Circuit_NextPCElement(void);
    DSS_CAPI_DLL int32_t Circuit_NextPDElement(void);
    DSS_CAPI_DLL void Circuit_Get_AllBusNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllElementLosses(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Sample(void);
    DSS_CAPI_DLL void Circuit_SaveSample(void);
    DSS_CAPI_DLL int32_t Circuit_SetActiveElement(char* FullName);
    DSS_CAPI_DLL double Circuit_Capacity(double Start, double Increment);
    DSS_CAPI_DLL void Circuit_Get_AllBusVmagPu(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Circuit_SetActiveBus(char* BusName);
    DSS_CAPI_DLL int32_t Circuit_SetActiveBusi(int32_t BusIndex);
    DSS_CAPI_DLL void Circuit_Get_AllNodeNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_SystemY(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllBusDistances(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllNodeDistances(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_AllNodeDistancesByPhase(double** ResultPtr, int32_t* ResultCount, int32_t Phase);
    DSS_CAPI_DLL void Circuit_Get_AllNodeVmagByPhase(double** ResultPtr, int32_t* ResultCount, int32_t Phase);
    DSS_CAPI_DLL void Circuit_Get_AllNodeVmagPUByPhase(double** ResultPtr, int32_t* ResultCount, int32_t Phase);
    DSS_CAPI_DLL void Circuit_Get_AllNodeNamesByPhase(char*** ResultPtr, int32_t* ResultCount, int32_t Phase);
    DSS_CAPI_DLL int32_t Circuit_SetActiveClass(char* ClassName);
    DSS_CAPI_DLL int32_t Circuit_FirstElement(void);
    DSS_CAPI_DLL int32_t Circuit_NextElement(void);
    DSS_CAPI_DLL void Circuit_UpdateStorage(void);
    DSS_CAPI_DLL int32_t Circuit_Get_ParentPDElement(void);
    DSS_CAPI_DLL void Circuit_EndOfTimeStepUpdate(void);
    DSS_CAPI_DLL void Circuit_Get_YNodeOrder(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_YCurrents(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Circuit_Get_YNodeVarray(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_BusNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* CktElement_Get_Name(void);
    DSS_CAPI_DLL int32_t CktElement_Get_NumConductors(void);
    DSS_CAPI_DLL int32_t CktElement_Get_NumPhases(void);
    DSS_CAPI_DLL int32_t CktElement_Get_NumTerminals(void);
    DSS_CAPI_DLL void CktElement_Set_BusNames(char** ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void CktElement_Get_Currents(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_Voltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double CktElement_Get_EmergAmps(void);
    DSS_CAPI_DLL uint16_t CktElement_Get_Enabled(void);
    DSS_CAPI_DLL void CktElement_Get_Losses(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double CktElement_Get_NormalAmps(void);
    DSS_CAPI_DLL void CktElement_Get_PhaseLosses(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_Powers(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_SeqCurrents(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_SeqPowers(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_SeqVoltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Close(int32_t Term, int32_t Phs);
    DSS_CAPI_DLL void CktElement_Open(int32_t Term, int32_t Phs);
    DSS_CAPI_DLL void CktElement_Set_EmergAmps(double Value);
    DSS_CAPI_DLL void CktElement_Set_Enabled(uint16_t Value);
    DSS_CAPI_DLL void CktElement_Set_NormalAmps(double Value);
    DSS_CAPI_DLL uint16_t CktElement_IsOpen(int32_t Term, int32_t Phs);
    DSS_CAPI_DLL void CktElement_Get_AllPropertyNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t CktElement_Get_NumProperties(void);
    DSS_CAPI_DLL void CktElement_Get_Residuals(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_Yprim(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* CktElement_Get_DisplayName(void);
    DSS_CAPI_DLL char* CktElement_Get_GUID(void);
    DSS_CAPI_DLL int32_t CktElement_Get_Handle(void);
    DSS_CAPI_DLL void CktElement_Set_DisplayName(char* Value);
    DSS_CAPI_DLL char* CktElement_Get_Controller(int32_t idx);
    DSS_CAPI_DLL char* CktElement_Get_EnergyMeter(void);
    DSS_CAPI_DLL uint16_t CktElement_Get_HasVoltControl(void);
    DSS_CAPI_DLL uint16_t CktElement_Get_HasSwitchControl(void);
    DSS_CAPI_DLL void CktElement_Get_CplxSeqVoltages(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_CplxSeqCurrents(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_AllVariableNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_AllVariableValues(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double CktElement_Get_Variable(char* MyVarName, int32_t Code);
    DSS_CAPI_DLL double CktElement_Get_Variablei(int32_t Idx, int32_t Code);
    DSS_CAPI_DLL void CktElement_Get_NodeOrder(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL uint16_t CktElement_Get_HasOCPDevice(void);
    DSS_CAPI_DLL int32_t CktElement_Get_NumControls(void);
    DSS_CAPI_DLL int32_t CktElement_Get_OCPDevIndex(void);
    DSS_CAPI_DLL int32_t CktElement_Get_OCPDevType(void);
    DSS_CAPI_DLL void CktElement_Get_CurrentsMagAng(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CktElement_Get_VoltagesMagAng(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void CmathLib_Get_cmplx(double** ResultPtr, int32_t* ResultCount, double RealPart, double ImagPart);
    DSS_CAPI_DLL double CmathLib_Get_cabs(double realpart, double imagpart);
    DSS_CAPI_DLL double CmathLib_Get_cdang(double RealPart, double ImagPart);
    DSS_CAPI_DLL void CmathLib_Get_ctopolardeg(double** ResultPtr, int32_t* ResultCount, double RealPart, double ImagPart);
    DSS_CAPI_DLL void CmathLib_Get_pdegtocomplex(double** ResultPtr, int32_t* ResultCount, double magnitude, double angle);
    DSS_CAPI_DLL void CmathLib_Get_cmul(double** ResultPtr, int32_t* ResultCount, double a1, double b1, double a2, double b2);
    DSS_CAPI_DLL void CmathLib_Get_cdiv(double** ResultPtr, int32_t* ResultCount, double a1, double b1, double a2, double b2);
    DSS_CAPI_DLL void CtrlQueue_ClearQueue(void);
    DSS_CAPI_DLL void CtrlQueue_Delete(int32_t ActionHandle);
    DSS_CAPI_DLL int32_t CtrlQueue_Get_ActionCode(void);
    DSS_CAPI_DLL int32_t CtrlQueue_Get_DeviceHandle(void);
    DSS_CAPI_DLL int32_t CtrlQueue_Get_NumActions(void);
    DSS_CAPI_DLL void CtrlQueue_Show(void);
    DSS_CAPI_DLL void CtrlQueue_ClearActions(void);
    DSS_CAPI_DLL int32_t CtrlQueue_Get_PopAction(void);
    DSS_CAPI_DLL void CtrlQueue_Set_Action(int32_t Param1);
    DSS_CAPI_DLL int32_t CtrlQueue_Get_QueueSize(void);
    DSS_CAPI_DLL void CtrlQueue_DoAllQueue(void);
    DSS_CAPI_DLL void CtrlQueue_Get_Queue(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t DSS_Get_NumCircuits(void);
    DSS_CAPI_DLL void DSS_ClearAll(void);
    DSS_CAPI_DLL char* DSS_Get_Version(void);
    DSS_CAPI_DLL uint16_t DSS_Start(int32_t code);
    DSS_CAPI_DLL void DSS_Get_Classes(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void DSS_Get_UserClasses(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t DSS_Get_NumClasses(void);
    DSS_CAPI_DLL int32_t DSS_Get_NumUserClasses(void);
    DSS_CAPI_DLL char* DSS_Get_DataPath(void);
    DSS_CAPI_DLL void DSS_Set_DataPath(char* Value);
    DSS_CAPI_DLL void DSS_Reset(void);
    DSS_CAPI_DLL char* DSS_Get_DefaultEditor(void);
    DSS_CAPI_DLL int32_t DSS_SetActiveClass(char* ClassName);
    DSS_CAPI_DLL void DSSElement_Get_AllPropertyNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* DSSElement_Get_Name(void);
    DSS_CAPI_DLL int32_t DSSElement_Get_NumProperties(void);
    DSS_CAPI_DLL void DSSimComs_BusVoltagepu(double** ResultPtr, int32_t* ResultCount, size_t Index);
    DSS_CAPI_DLL void DSSimComs_BusVoltage(double** ResultPtr, int32_t* ResultCount, size_t Index);
    DSS_CAPI_DLL void DSSProgress_Close(void);
    DSS_CAPI_DLL void DSSProgress_Set_Caption(char* Value);
    DSS_CAPI_DLL void DSSProgress_Set_PctProgress(int32_t Value);
    DSS_CAPI_DLL void DSSProgress_Show(void);
    DSS_CAPI_DLL char* DSSProperty_Get_Description(void);
    DSS_CAPI_DLL char* DSSProperty_Get_Name(void);
    DSS_CAPI_DLL char* DSSProperty_Get_Val(void);
    DSS_CAPI_DLL void DSSProperty_Set_Val(char* Value);
    DSS_CAPI_DLL char* DSS_Executive_Get_Command(int32_t i);
    DSS_CAPI_DLL int32_t DSS_Executive_Get_NumCommands(void);
    DSS_CAPI_DLL int32_t DSS_Executive_Get_NumOptions(void);
    DSS_CAPI_DLL char* DSS_Executive_Get_Option(int32_t i);
    DSS_CAPI_DLL char* DSS_Executive_Get_CommandHelp(int32_t i);
    DSS_CAPI_DLL char* DSS_Executive_Get_OptionHelp(int32_t i);
    DSS_CAPI_DLL char* DSS_Executive_Get_OptionValue(int32_t i);
    DSS_CAPI_DLL char* Error_Get_Description(void);
    DSS_CAPI_DLL int32_t Error_Get_Number(void);
    DSS_CAPI_DLL void Fuses_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Fuses_Get_Count(void);
    DSS_CAPI_DLL int32_t Fuses_Get_First(void);
    DSS_CAPI_DLL char* Fuses_Get_Name(void);
    DSS_CAPI_DLL int32_t Fuses_Get_Next(void);
    DSS_CAPI_DLL void Fuses_Set_Name(char* Value);
    DSS_CAPI_DLL char* Fuses_Get_MonitoredObj(void);
    DSS_CAPI_DLL int32_t Fuses_Get_MonitoredTerm(void);
    DSS_CAPI_DLL char* Fuses_Get_SwitchedObj(void);
    DSS_CAPI_DLL void Fuses_Set_MonitoredObj(char* Value);
    DSS_CAPI_DLL void Fuses_Set_MonitoredTerm(int32_t Value);
    DSS_CAPI_DLL void Fuses_Set_SwitchedObj(char* Value);
    DSS_CAPI_DLL int32_t Fuses_Get_SwitchedTerm(void);
    DSS_CAPI_DLL void Fuses_Set_SwitchedTerm(int32_t Value);
    DSS_CAPI_DLL char* Fuses_Get_TCCcurve(void);
    DSS_CAPI_DLL void Fuses_Set_TCCcurve(char* Value);
    DSS_CAPI_DLL double Fuses_Get_RatedCurrent(void);
    DSS_CAPI_DLL void Fuses_Set_RatedCurrent(double Value);
    DSS_CAPI_DLL double Fuses_Get_Delay(void);
    DSS_CAPI_DLL void Fuses_Open(void);
    DSS_CAPI_DLL void Fuses_Close(void);
    DSS_CAPI_DLL void Fuses_Set_Delay(double Value);
    DSS_CAPI_DLL int32_t Fuses_Get_idx(void);
    DSS_CAPI_DLL void Fuses_Set_idx(int32_t Value);
    DSS_CAPI_DLL int32_t Fuses_Get_NumPhases(void);
    DSS_CAPI_DLL void Generators_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Generators_Get_First(void);
    DSS_CAPI_DLL char* Generators_Get_Name(void);
    DSS_CAPI_DLL int32_t Generators_Get_Next(void);
    DSS_CAPI_DLL void Generators_Get_RegisterNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Generators_Get_RegisterValues(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL uint16_t Generators_Get_ForcedON(void);
    DSS_CAPI_DLL void Generators_Set_ForcedON(uint16_t Value);
    DSS_CAPI_DLL void Generators_Set_Name(char* Value);
    DSS_CAPI_DLL double Generators_Get_kV(void);
    DSS_CAPI_DLL double Generators_Get_kvar(void);
    DSS_CAPI_DLL double Generators_Get_kW(void);
    DSS_CAPI_DLL double Generators_Get_PF(void);
    DSS_CAPI_DLL int32_t Generators_Get_Phases(void);
    DSS_CAPI_DLL void Generators_Set_kV(double Value);
    DSS_CAPI_DLL void Generators_Set_kvar(double Value);
    DSS_CAPI_DLL void Generators_Set_kW(double Value);
    DSS_CAPI_DLL void Generators_Set_PF(double Value);
    DSS_CAPI_DLL void Generators_Set_Phases(int32_t Value);
    DSS_CAPI_DLL int32_t Generators_Get_Count(void);
    DSS_CAPI_DLL int32_t Generators_Get_idx(void);
    DSS_CAPI_DLL void Generators_Set_idx(int32_t Value);
    DSS_CAPI_DLL int32_t Generators_Get_Model(void);
    DSS_CAPI_DLL void Generators_Set_Model(int32_t Value);
    DSS_CAPI_DLL double Generators_Get_kVArated(void);
    DSS_CAPI_DLL void Generators_Set_kVArated(double Value);
    DSS_CAPI_DLL double Generators_Get_Vmaxpu(void);
    DSS_CAPI_DLL double Generators_Get_Vminpu(void);
    DSS_CAPI_DLL void Generators_Set_Vmaxpu(double Value);
    DSS_CAPI_DLL void Generators_Set_Vminpu(double Value);
    DSS_CAPI_DLL void ISources_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t ISources_Get_Count(void);
    DSS_CAPI_DLL int32_t ISources_Get_First(void);
    DSS_CAPI_DLL int32_t ISources_Get_Next(void);
    DSS_CAPI_DLL char* ISources_Get_Name(void);
    DSS_CAPI_DLL void ISources_Set_Name(char* Value);
    DSS_CAPI_DLL double ISources_Get_Amps(void);
    DSS_CAPI_DLL void ISources_Set_Amps(double Value);
    DSS_CAPI_DLL double ISources_Get_AngleDeg(void);
    DSS_CAPI_DLL double ISources_Get_Frequency(void);
    DSS_CAPI_DLL void ISources_Set_AngleDeg(double Value);
    DSS_CAPI_DLL void ISources_Set_Frequency(double Value);
    DSS_CAPI_DLL int32_t LineCodes_Get_Count(void);
    DSS_CAPI_DLL int32_t LineCodes_Get_First(void);
    DSS_CAPI_DLL int32_t LineCodes_Get_Next(void);
    DSS_CAPI_DLL char* LineCodes_Get_Name(void);
    DSS_CAPI_DLL void LineCodes_Set_Name(char* Value);
    DSS_CAPI_DLL uint16_t LineCodes_Get_IsZ1Z0(void);
    DSS_CAPI_DLL int32_t LineCodes_Get_Units(void);
    DSS_CAPI_DLL void LineCodes_Set_Units(int32_t Value);
    DSS_CAPI_DLL int32_t LineCodes_Get_Phases(void);
    DSS_CAPI_DLL void LineCodes_Set_Phases(int32_t Value);
    DSS_CAPI_DLL double LineCodes_Get_R1(void);
    DSS_CAPI_DLL void LineCodes_Set_R1(double Value);
    DSS_CAPI_DLL double LineCodes_Get_X1(void);
    DSS_CAPI_DLL void LineCodes_Set_X1(double Value);
    DSS_CAPI_DLL double LineCodes_Get_R0(void);
    DSS_CAPI_DLL double LineCodes_Get_X0(void);
    DSS_CAPI_DLL void LineCodes_Set_R0(double Value);
    DSS_CAPI_DLL void LineCodes_Set_X0(double Value);
    DSS_CAPI_DLL double LineCodes_Get_C0(void);
    DSS_CAPI_DLL double LineCodes_Get_C1(void);
    DSS_CAPI_DLL void LineCodes_Set_C0(double Value);
    DSS_CAPI_DLL void LineCodes_Set_C1(double Value);
    DSS_CAPI_DLL void LineCodes_Get_Cmatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void LineCodes_Get_Rmatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void LineCodes_Get_Xmatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void LineCodes_Set_Cmatrix(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void LineCodes_Set_Rmatrix(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void LineCodes_Set_Xmatrix(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL double LineCodes_Get_NormAmps(void);
    DSS_CAPI_DLL void LineCodes_Set_NormAmps(double Value);
    DSS_CAPI_DLL double LineCodes_Get_EmergAmps(void);
    DSS_CAPI_DLL void LineCodes_Set_EmergAmps(double Value);
    DSS_CAPI_DLL void LineCodes_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Lines_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* Lines_Get_Bus1(void);
    DSS_CAPI_DLL char* Lines_Get_Bus2(void);
    DSS_CAPI_DLL int32_t Lines_Get_First(void);
    DSS_CAPI_DLL double Lines_Get_Length(void);
    DSS_CAPI_DLL char* Lines_Get_LineCode(void);
    DSS_CAPI_DLL char* Lines_Get_Name(void);
    DSS_CAPI_DLL int32_t Lines_Get_Next(void);
    DSS_CAPI_DLL int32_t Lines_Get_Phases(void);
    DSS_CAPI_DLL double Lines_Get_R1(void);
    DSS_CAPI_DLL double Lines_Get_X1(void);
    DSS_CAPI_DLL int32_t Lines_New(char* Name);
    DSS_CAPI_DLL void Lines_Set_Bus1(char* Value);
    DSS_CAPI_DLL void Lines_Set_Bus2(char* Value);
    DSS_CAPI_DLL void Lines_Set_Length(double Value);
    DSS_CAPI_DLL void Lines_Set_LineCode(char* Value);
    DSS_CAPI_DLL void Lines_Set_Name(char* Value);
    DSS_CAPI_DLL void Lines_Set_Phases(int32_t Value);
    DSS_CAPI_DLL void Lines_Set_R1(double Value);
    DSS_CAPI_DLL void Lines_Set_X1(double Value);
    DSS_CAPI_DLL double Lines_Get_C0(void);
    DSS_CAPI_DLL double Lines_Get_C1(void);
    DSS_CAPI_DLL void Lines_Get_Cmatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Lines_Get_R0(void);
    DSS_CAPI_DLL void Lines_Get_Rmatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Lines_Get_X0(void);
    DSS_CAPI_DLL void Lines_Get_Xmatrix(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Lines_Set_C0(double Value);
    DSS_CAPI_DLL void Lines_Set_C1(double Value);
    DSS_CAPI_DLL void Lines_Set_Cmatrix(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Lines_Set_R0(double Value);
    DSS_CAPI_DLL void Lines_Set_Rmatrix(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Lines_Set_X0(double Value);
    DSS_CAPI_DLL void Lines_Set_Xmatrix(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL double Lines_Get_EmergAmps(void);
    DSS_CAPI_DLL double Lines_Get_NormAmps(void);
    DSS_CAPI_DLL void Lines_Set_EmergAmps(double Value);
    DSS_CAPI_DLL void Lines_Set_NormAmps(double Value);
    DSS_CAPI_DLL char* Lines_Get_Geometry(void);
    DSS_CAPI_DLL void Lines_Set_Geometry(char* Value);
    DSS_CAPI_DLL double Lines_Get_Rg(void);
    DSS_CAPI_DLL double Lines_Get_Rho(void);
    DSS_CAPI_DLL double Lines_Get_Xg(void);
    DSS_CAPI_DLL void Lines_Set_Rg(double Value);
    DSS_CAPI_DLL void Lines_Set_Rho(double Value);
    DSS_CAPI_DLL void Lines_Set_Xg(double Value);
    DSS_CAPI_DLL void Lines_Get_Yprim(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Lines_Set_Yprim(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL int32_t Lines_Get_NumCust(void);
    DSS_CAPI_DLL int32_t Lines_Get_TotalCust(void);
    DSS_CAPI_DLL int32_t Lines_Get_Parent(void);
    DSS_CAPI_DLL int32_t Lines_Get_Count(void);
    DSS_CAPI_DLL char* Lines_Get_Spacing(void);
    DSS_CAPI_DLL void Lines_Set_Spacing(char* Value);
    DSS_CAPI_DLL int32_t Lines_Get_Units(void);
    DSS_CAPI_DLL void Lines_Set_Units(int32_t Value);
    DSS_CAPI_DLL void Loads_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Loads_Get_First(void);
    DSS_CAPI_DLL int32_t Loads_Get_idx(void);
    DSS_CAPI_DLL char* Loads_Get_Name(void);
    DSS_CAPI_DLL int32_t Loads_Get_Next(void);
    DSS_CAPI_DLL void Loads_Set_idx(int32_t Value);
    DSS_CAPI_DLL void Loads_Set_Name(char* Value);
    DSS_CAPI_DLL double Loads_Get_kV(void);
    DSS_CAPI_DLL double Loads_Get_kvar(void);
    DSS_CAPI_DLL double Loads_Get_kW(void);
    DSS_CAPI_DLL double Loads_Get_PF(void);
    DSS_CAPI_DLL void Loads_Set_kV(double Value);
    DSS_CAPI_DLL void Loads_Set_kvar(double Value);
    DSS_CAPI_DLL void Loads_Set_kW(double Value);
    DSS_CAPI_DLL void Loads_Set_PF(double Value);
    DSS_CAPI_DLL int32_t Loads_Get_Count(void);
    DSS_CAPI_DLL double Loads_Get_AllocationFactor(void);
    DSS_CAPI_DLL double Loads_Get_Cfactor(void);
    DSS_CAPI_DLL int32_t Loads_Get_Class_(void);
    DSS_CAPI_DLL char* Loads_Get_CVRcurve(void);
    DSS_CAPI_DLL double Loads_Get_CVRvars(void);
    DSS_CAPI_DLL double Loads_Get_CVRwatts(void);
    DSS_CAPI_DLL char* Loads_Get_daily(void);
    DSS_CAPI_DLL char* Loads_Get_duty(void);
    DSS_CAPI_DLL char* Loads_Get_Growth(void);
    DSS_CAPI_DLL uint16_t Loads_Get_IsDelta(void);
    DSS_CAPI_DLL double Loads_Get_kva(void);
    DSS_CAPI_DLL double Loads_Get_kwh(void);
    DSS_CAPI_DLL double Loads_Get_kwhdays(void);
    DSS_CAPI_DLL int32_t Loads_Get_Model(void);
    DSS_CAPI_DLL int32_t Loads_Get_NumCust(void);
    DSS_CAPI_DLL double Loads_Get_PctMean(void);
    DSS_CAPI_DLL double Loads_Get_PctStdDev(void);
    DSS_CAPI_DLL double Loads_Get_Rneut(void);
    DSS_CAPI_DLL char* Loads_Get_Spectrum(void);
    DSS_CAPI_DLL int32_t Loads_Get_Status(void);
    DSS_CAPI_DLL double Loads_Get_Vmaxpu(void);
    DSS_CAPI_DLL double Loads_Get_Vminemerg(void);
    DSS_CAPI_DLL double Loads_Get_Vminnorm(void);
    DSS_CAPI_DLL double Loads_Get_Vminpu(void);
    DSS_CAPI_DLL double Loads_Get_xfkVA(void);
    DSS_CAPI_DLL double Loads_Get_Xneut(void);
    DSS_CAPI_DLL char* Loads_Get_Yearly(void);
    DSS_CAPI_DLL void Loads_Set_AllocationFactor(double Value);
    DSS_CAPI_DLL void Loads_Set_Cfactor(double Value);
    DSS_CAPI_DLL void Loads_Set_Class_(int32_t Value);
    DSS_CAPI_DLL void Loads_Set_CVRcurve(char* Value);
    DSS_CAPI_DLL void Loads_Set_CVRvars(double Value);
    DSS_CAPI_DLL void Loads_Set_CVRwatts(double Value);
    DSS_CAPI_DLL void Loads_Set_daily(char* Value);
    DSS_CAPI_DLL void Loads_Set_duty(char* Value);
    DSS_CAPI_DLL void Loads_Set_Growth(char* Value);
    DSS_CAPI_DLL void Loads_Set_IsDelta(uint16_t Value);
    DSS_CAPI_DLL void Loads_Set_kva(double Value);
    DSS_CAPI_DLL void Loads_Set_kwh(double Value);
    DSS_CAPI_DLL void Loads_Set_kwhdays(double Value);
    DSS_CAPI_DLL void Loads_Set_Model(int32_t Value);
    DSS_CAPI_DLL void Loads_Set_NumCust(int32_t Value);
    DSS_CAPI_DLL void Loads_Set_PctMean(double Value);
    DSS_CAPI_DLL void Loads_Set_PctStdDev(double Value);
    DSS_CAPI_DLL void Loads_Set_Rneut(double Value);
    DSS_CAPI_DLL void Loads_Set_Spectrum(char* Value);
    DSS_CAPI_DLL void Loads_Set_Status(int32_t Value);
    DSS_CAPI_DLL void Loads_Set_Vmaxpu(double Value);
    DSS_CAPI_DLL void Loads_Set_Vminemerg(double Value);
    DSS_CAPI_DLL void Loads_Set_Vminnorm(double Value);
    DSS_CAPI_DLL void Loads_Set_Vminpu(double Value);
    DSS_CAPI_DLL void Loads_Set_xfkVA(double Value);
    DSS_CAPI_DLL void Loads_Set_Xneut(double Value);
    DSS_CAPI_DLL void Loads_Set_Yearly(char* Value);
    DSS_CAPI_DLL void Loads_Get_ZIPV(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Loads_Set_ZIPV(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL double Loads_Get_pctSeriesRL(void);
    DSS_CAPI_DLL void Loads_Set_pctSeriesRL(double Value);
    DSS_CAPI_DLL double Loads_Get_RelWeight(void);
    DSS_CAPI_DLL char* LoadShapes_Get_Name(void);
    DSS_CAPI_DLL void LoadShapes_Set_Name(char* Value);
    DSS_CAPI_DLL int32_t LoadShapes_Get_Count(void);
    DSS_CAPI_DLL int32_t LoadShapes_Get_First(void);
    DSS_CAPI_DLL int32_t LoadShapes_Get_Next(void);
    DSS_CAPI_DLL void LoadShapes_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t LoadShapes_Get_Npts(void);
    DSS_CAPI_DLL void LoadShapes_Get_Pmult(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void LoadShapes_Get_Qmult(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void LoadShapes_Set_Npts(int32_t Value);
    DSS_CAPI_DLL void LoadShapes_Set_Pmult(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void LoadShapes_Set_Qmult(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void LoadShapes_Normalize(void);
    DSS_CAPI_DLL void LoadShapes_Get_TimeArray(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void LoadShapes_Set_TimeArray(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL double LoadShapes_Get_HrInterval(void);
    DSS_CAPI_DLL double LoadShapes_Get_MinInterval(void);
    DSS_CAPI_DLL double LoadShapes_Get_sInterval(void);
    DSS_CAPI_DLL void LoadShapes_Set_HrInterval(double Value);
    DSS_CAPI_DLL void LoadShapes_Set_MinInterval(double Value);
    DSS_CAPI_DLL void LoadShapes_Set_Sinterval(double Value);
    DSS_CAPI_DLL double LoadShapes_Get_PBase(void);
    DSS_CAPI_DLL double LoadShapes_Get_Qbase(void);
    DSS_CAPI_DLL void LoadShapes_Set_PBase(double Value);
    DSS_CAPI_DLL void LoadShapes_Set_Qbase(double Value);
    DSS_CAPI_DLL uint16_t LoadShapes_Get_UseActual(void);
    DSS_CAPI_DLL void LoadShapes_Set_UseActual(uint16_t Value);
    DSS_CAPI_DLL void Meters_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Meters_Get_First(void);
    DSS_CAPI_DLL char* Meters_Get_Name(void);
    DSS_CAPI_DLL int32_t Meters_Get_Next(void);
    DSS_CAPI_DLL void Meters_Get_RegisterNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Meters_Get_RegisterValues(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Meters_Reset(void);
    DSS_CAPI_DLL void Meters_ResetAll(void);
    DSS_CAPI_DLL void Meters_Sample(void);
    DSS_CAPI_DLL void Meters_Save(void);
    DSS_CAPI_DLL void Meters_Set_Name(char* Value);
    DSS_CAPI_DLL void Meters_Get_Totals(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Meters_Get_Peakcurrent(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Meters_Set_Peakcurrent(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Meters_Get_CalcCurrent(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Meters_Set_CalcCurrent(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Meters_Get_AllocFactors(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Meters_Set_AllocFactors(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL char* Meters_Get_MeteredElement(void);
    DSS_CAPI_DLL int32_t Meters_Get_MeteredTerminal(void);
    DSS_CAPI_DLL void Meters_Set_MeteredElement(char* Value);
    DSS_CAPI_DLL void Meters_Set_MeteredTerminal(int32_t Value);
    DSS_CAPI_DLL uint16_t Meters_Get_DIFilesAreOpen(void);
    DSS_CAPI_DLL void Meters_CloseAllDIFiles(void);
    DSS_CAPI_DLL void Meters_OpenAllDIFiles(void);
    DSS_CAPI_DLL void Meters_SampleAll(void);
    DSS_CAPI_DLL void Meters_SaveAll(void);
    DSS_CAPI_DLL void Meters_Get_AllEndElements(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Meters_Get_CountEndElements(void);
    DSS_CAPI_DLL int32_t Meters_Get_Count(void);
    DSS_CAPI_DLL void Meters_Get_AllBranchesInZone(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Meters_Get_CountBranches(void);
    DSS_CAPI_DLL double Meters_Get_SAIFI(void);
    DSS_CAPI_DLL int32_t Meters_Get_SequenceIndex(void);
    DSS_CAPI_DLL void Meters_Set_SequenceIndex(int32_t Value);
    DSS_CAPI_DLL double Meters_Get_SAIFIKW(void);
    DSS_CAPI_DLL void Meters_DoReliabilityCalc(uint16_t AssumeRestoration);
    DSS_CAPI_DLL int32_t Meters_Get_SeqListSize(void);
    DSS_CAPI_DLL int32_t Meters_Get_TotalCustomers(void);
    DSS_CAPI_DLL double Meters_Get_SAIDI(void);
    DSS_CAPI_DLL double Meters_Get_CustInterrupts(void);
    DSS_CAPI_DLL int32_t Meters_Get_NumSections(void);
    DSS_CAPI_DLL void Meters_SetActiveSection(int32_t SectIdx);
    DSS_CAPI_DLL double Meters_Get_AvgRepairTime(void);
    DSS_CAPI_DLL double Meters_Get_FaultRateXRepairHrs(void);
    DSS_CAPI_DLL int32_t Meters_Get_NumSectionBranches(void);
    DSS_CAPI_DLL int32_t Meters_Get_NumSectionCustomers(void);
    DSS_CAPI_DLL int32_t Meters_Get_OCPDeviceType(void);
    DSS_CAPI_DLL double Meters_Get_SumBranchFltRates(void);
    DSS_CAPI_DLL int32_t Meters_Get_SectSeqIdx(void);
    DSS_CAPI_DLL int32_t Meters_Get_SectTotalCust(void);
    DSS_CAPI_DLL void Monitors_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* Monitors_Get_FileName(void);
    DSS_CAPI_DLL int32_t Monitors_Get_First(void);
    DSS_CAPI_DLL int32_t Monitors_Get_Mode(void);
    DSS_CAPI_DLL char* Monitors_Get_Name(void);
    DSS_CAPI_DLL int32_t Monitors_Get_Next(void);
    DSS_CAPI_DLL void Monitors_Reset(void);
    DSS_CAPI_DLL void Monitors_ResetAll(void);
    DSS_CAPI_DLL void Monitors_Sample(void);
    DSS_CAPI_DLL void Monitors_Save(void);
    DSS_CAPI_DLL void Monitors_Set_Mode(int32_t Value);
    DSS_CAPI_DLL void Monitors_Show(void);
    DSS_CAPI_DLL void Monitors_Set_Name(char* Value);
    DSS_CAPI_DLL void Monitors_Get_ByteStream(int8_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Monitors_Get_SampleCount(void);
    DSS_CAPI_DLL void Monitors_SampleAll(void);
    DSS_CAPI_DLL void Monitors_SaveAll(void);
    DSS_CAPI_DLL int32_t Monitors_Get_Count(void);
    DSS_CAPI_DLL void Monitors_Process(void);
    DSS_CAPI_DLL void Monitors_ProcessAll(void);
    DSS_CAPI_DLL void Monitors_Get_Channel(double** ResultPtr, int32_t* ResultCount, int32_t Index);
    DSS_CAPI_DLL void Monitors_Get_dblFreq(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Monitors_Get_dblHour(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Monitors_Get_FileVersion(void);
    DSS_CAPI_DLL void Monitors_Get_Header(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Monitors_Get_NumChannels(void);
    DSS_CAPI_DLL int32_t Monitors_Get_RecordSize(void);
    DSS_CAPI_DLL char* Monitors_Get_Element(void);
    DSS_CAPI_DLL void Monitors_Set_Element(char* Value);
    DSS_CAPI_DLL int32_t Monitors_Get_Terminal(void);
    DSS_CAPI_DLL void Monitors_Set_Terminal(int32_t Value);
    DSS_CAPI_DLL int32_t Parallel_Get_NumCPUs(void);
    DSS_CAPI_DLL int32_t Parallel_Get_NumCores(void);
    DSS_CAPI_DLL int32_t Parallel_Get_ActiveActor(void);
    DSS_CAPI_DLL void Parallel_Set_ActiveActor(int32_t Value);
    DSS_CAPI_DLL void Parallel_CreateActor(void);
    DSS_CAPI_DLL int32_t Parallel_Get_ActorCPU(void);
    DSS_CAPI_DLL void Parallel_Set_ActorCPU(int32_t Value);
    DSS_CAPI_DLL int32_t Parallel_Get_NumOfActors(void);
    DSS_CAPI_DLL void Parallel_Wait(void);
    DSS_CAPI_DLL void Parallel_Get_ActorProgress(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Parallel_Get_ActorStatus(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Parallel_Get_ActiveParallel(void);
    DSS_CAPI_DLL void Parallel_Set_ActiveParallel(int32_t Value);
    DSS_CAPI_DLL int32_t Parallel_Get_ConcatenateReports(void);
    DSS_CAPI_DLL void Parallel_Set_ConcatenateReports(int32_t Value);
    DSS_CAPI_DLL char* Parser_Get_CmdString(void);
    DSS_CAPI_DLL void Parser_Set_CmdString(char* Value);
    DSS_CAPI_DLL char* Parser_Get_NextParam(void);
    DSS_CAPI_DLL uint16_t Parser_Get_AutoIncrement(void);
    DSS_CAPI_DLL void Parser_Set_AutoIncrement(uint16_t Value);
    DSS_CAPI_DLL double Parser_Get_DblValue(void);
    DSS_CAPI_DLL int32_t Parser_Get_IntValue(void);
    DSS_CAPI_DLL char* Parser_Get_StrValue(void);
    DSS_CAPI_DLL char* Parser_Get_WhiteSpace(void);
    DSS_CAPI_DLL void Parser_Set_WhiteSpace(char* Value);
    DSS_CAPI_DLL char* Parser_Get_BeginQuote(void);
    DSS_CAPI_DLL char* Parser_Get_EndQuote(void);
    DSS_CAPI_DLL void Parser_Set_BeginQuote(char* Value);
    DSS_CAPI_DLL void Parser_Set_EndQuote(char* Value);
    DSS_CAPI_DLL char* Parser_Get_Delimiters(void);
    DSS_CAPI_DLL void Parser_Set_Delimiters(char* Value);
    DSS_CAPI_DLL void Parser_ResetDelimiters(void);
    DSS_CAPI_DLL void Parser_Get_Vector(double** ResultPtr, int32_t* ResultCount, int32_t ExpectedSize);
    DSS_CAPI_DLL void Parser_Get_Matrix(double** ResultPtr, int32_t* ResultCount, int32_t ExpectedOrder);
    DSS_CAPI_DLL void Parser_Get_SymMatrix(double** ResultPtr, int32_t* ResultCount, int32_t ExpectedOrder);
    DSS_CAPI_DLL int32_t PDElements_Get_Count(void);
    DSS_CAPI_DLL double PDElements_Get_FaultRate(void);
    DSS_CAPI_DLL int32_t PDElements_Get_First(void);
    DSS_CAPI_DLL uint16_t PDElements_Get_IsShunt(void);
    DSS_CAPI_DLL int32_t PDElements_Get_Next(void);
    DSS_CAPI_DLL double PDElements_Get_pctPermanent(void);
    DSS_CAPI_DLL void PDElements_Set_FaultRate(double Value);
    DSS_CAPI_DLL void PDElements_Set_pctPermanent(double Value);
    DSS_CAPI_DLL char* PDElements_Get_Name(void);
    DSS_CAPI_DLL void PDElements_Set_Name(char* Value);
    DSS_CAPI_DLL double PDElements_Get_AccumulatedL(void);
    DSS_CAPI_DLL double PDElements_Get_Lambda(void);
    DSS_CAPI_DLL int32_t PDElements_Get_Numcustomers(void);
    DSS_CAPI_DLL int32_t PDElements_Get_ParentPDElement(void);
    DSS_CAPI_DLL double PDElements_Get_RepairTime(void);
    DSS_CAPI_DLL int32_t PDElements_Get_Totalcustomers(void);
    DSS_CAPI_DLL int32_t PDElements_Get_FromTerminal(void);
    DSS_CAPI_DLL double PDElements_Get_TotalMiles(void);
    DSS_CAPI_DLL int32_t PDElements_Get_SectionID(void);
    DSS_CAPI_DLL void PDElements_Set_RepairTime(double Value);
    DSS_CAPI_DLL void PVSystems_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void PVSystems_Get_RegisterNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void PVSystems_Get_RegisterValues(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t PVSystems_Get_First(void);
    DSS_CAPI_DLL int32_t PVSystems_Get_Next(void);
    DSS_CAPI_DLL int32_t PVSystems_Get_Count(void);
    DSS_CAPI_DLL int32_t PVSystems_Get_idx(void);
    DSS_CAPI_DLL void PVSystems_Set_idx(int32_t Value);
    DSS_CAPI_DLL char* PVSystems_Get_Name(void);
    DSS_CAPI_DLL void PVSystems_Set_Name(char* Value);
    DSS_CAPI_DLL double PVSystems_Get_Irradiance(void);
    DSS_CAPI_DLL void PVSystems_Set_Irradiance(double Value);
    DSS_CAPI_DLL double PVSystems_Get_kvar(void);
    DSS_CAPI_DLL double PVSystems_Get_kVArated(void);
    DSS_CAPI_DLL double PVSystems_Get_kW(void);
    DSS_CAPI_DLL double PVSystems_Get_PF(void);
    DSS_CAPI_DLL void Reclosers_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Reclosers_Get_Count(void);
    DSS_CAPI_DLL int32_t Reclosers_Get_First(void);
    DSS_CAPI_DLL char* Reclosers_Get_Name(void);
    DSS_CAPI_DLL int32_t Reclosers_Get_Next(void);
    DSS_CAPI_DLL void Reclosers_Set_Name(char* Value);
    DSS_CAPI_DLL int32_t Reclosers_Get_MonitoredTerm(void);
    DSS_CAPI_DLL void Reclosers_Set_MonitoredTerm(int32_t Value);
    DSS_CAPI_DLL char* Reclosers_Get_SwitchedObj(void);
    DSS_CAPI_DLL void Reclosers_Set_SwitchedObj(char* Value);
    DSS_CAPI_DLL char* Reclosers_Get_MonitoredObj(void);
    DSS_CAPI_DLL int32_t Reclosers_Get_SwitchedTerm(void);
    DSS_CAPI_DLL void Reclosers_Set_MonitoredObj(char* Value);
    DSS_CAPI_DLL void Reclosers_Set_SwitchedTerm(int32_t Value);
    DSS_CAPI_DLL int32_t Reclosers_Get_NumFast(void);
    DSS_CAPI_DLL void Reclosers_Get_RecloseIntervals(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Reclosers_Get_Shots(void);
    DSS_CAPI_DLL void Reclosers_Set_NumFast(int32_t Value);
    DSS_CAPI_DLL void Reclosers_Set_Shots(int32_t Value);
    DSS_CAPI_DLL double Reclosers_Get_PhaseTrip(void);
    DSS_CAPI_DLL void Reclosers_Set_PhaseTrip(double Value);
    DSS_CAPI_DLL double Reclosers_Get_GroundInst(void);
    DSS_CAPI_DLL double Reclosers_Get_GroundTrip(void);
    DSS_CAPI_DLL double Reclosers_Get_PhaseInst(void);
    DSS_CAPI_DLL void Reclosers_Set_GroundInst(double Value);
    DSS_CAPI_DLL void Reclosers_Set_GroundTrip(double Value);
    DSS_CAPI_DLL void Reclosers_Set_PhaseInst(double Value);
    DSS_CAPI_DLL void Reclosers_Close(void);
    DSS_CAPI_DLL void Reclosers_Open(void);
    DSS_CAPI_DLL int32_t Reclosers_Get_idx(void);
    DSS_CAPI_DLL void Reclosers_Set_idx(int32_t Value);
    DSS_CAPI_DLL void RegControls_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double RegControls_Get_CTPrimary(void);
    DSS_CAPI_DLL double RegControls_Get_Delay(void);
    DSS_CAPI_DLL int32_t RegControls_Get_First(void);
    DSS_CAPI_DLL double RegControls_Get_ForwardBand(void);
    DSS_CAPI_DLL double RegControls_Get_ForwardR(void);
    DSS_CAPI_DLL double RegControls_Get_ForwardVreg(void);
    DSS_CAPI_DLL double RegControls_Get_ForwardX(void);
    DSS_CAPI_DLL uint16_t RegControls_Get_IsInverseTime(void);
    DSS_CAPI_DLL uint16_t RegControls_Get_IsReversible(void);
    DSS_CAPI_DLL int32_t RegControls_Get_MaxTapChange(void);
    DSS_CAPI_DLL char* RegControls_Get_MonitoredBus(void);
    DSS_CAPI_DLL char* RegControls_Get_Name(void);
    DSS_CAPI_DLL int32_t RegControls_Get_Next(void);
    DSS_CAPI_DLL double RegControls_Get_PTratio(void);
    DSS_CAPI_DLL double RegControls_Get_ReverseBand(void);
    DSS_CAPI_DLL double RegControls_Get_ReverseR(void);
    DSS_CAPI_DLL double RegControls_Get_ReverseVreg(void);
    DSS_CAPI_DLL double RegControls_Get_ReverseX(void);
    DSS_CAPI_DLL double RegControls_Get_TapDelay(void);
    DSS_CAPI_DLL int32_t RegControls_Get_TapWinding(void);
    DSS_CAPI_DLL char* RegControls_Get_Transformer(void);
    DSS_CAPI_DLL double RegControls_Get_VoltageLimit(void);
    DSS_CAPI_DLL int32_t RegControls_Get_Winding(void);
    DSS_CAPI_DLL int32_t RegControls_Get_TapNumber(void);
    DSS_CAPI_DLL void RegControls_Set_CTPrimary(double Value);
    DSS_CAPI_DLL void RegControls_Set_Delay(double Value);
    DSS_CAPI_DLL void RegControls_Set_ForwardBand(double Value);
    DSS_CAPI_DLL void RegControls_Set_ForwardR(double Value);
    DSS_CAPI_DLL void RegControls_Set_ForwardVreg(double Value);
    DSS_CAPI_DLL void RegControls_Set_ForwardX(double Value);
    DSS_CAPI_DLL void RegControls_Set_IsInverseTime(uint16_t Value);
    DSS_CAPI_DLL void RegControls_Set_IsReversible(uint16_t Value);
    DSS_CAPI_DLL void RegControls_Set_MaxTapChange(int32_t Value);
    DSS_CAPI_DLL void RegControls_Set_MonitoredBus(char* Value);
    DSS_CAPI_DLL void RegControls_Set_Name(char* Value);
    DSS_CAPI_DLL void RegControls_Set_PTratio(double Value);
    DSS_CAPI_DLL void RegControls_Set_ReverseBand(double Value);
    DSS_CAPI_DLL void RegControls_Set_ReverseR(double Value);
    DSS_CAPI_DLL void RegControls_Set_ReverseVreg(double Value);
    DSS_CAPI_DLL void RegControls_Set_ReverseX(double Value);
    DSS_CAPI_DLL void RegControls_Set_TapDelay(double Value);
    DSS_CAPI_DLL void RegControls_Set_TapWinding(int32_t Value);
    DSS_CAPI_DLL void RegControls_Set_Transformer(char* Value);
    DSS_CAPI_DLL void RegControls_Set_VoltageLimit(double Value);
    DSS_CAPI_DLL void RegControls_Set_Winding(int32_t Value);
    DSS_CAPI_DLL void RegControls_Set_TapNumber(int32_t Value);
    DSS_CAPI_DLL int32_t RegControls_Get_Count(void);
    DSS_CAPI_DLL void RegControls_Reset(void);
    DSS_CAPI_DLL void Relays_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Relays_Get_Count(void);
    DSS_CAPI_DLL int32_t Relays_Get_First(void);
    DSS_CAPI_DLL char* Relays_Get_Name(void);
    DSS_CAPI_DLL int32_t Relays_Get_Next(void);
    DSS_CAPI_DLL void Relays_Set_Name(char* Value);
    DSS_CAPI_DLL char* Relays_Get_MonitoredObj(void);
    DSS_CAPI_DLL void Relays_Set_MonitoredObj(char* Value);
    DSS_CAPI_DLL int32_t Relays_Get_MonitoredTerm(void);
    DSS_CAPI_DLL char* Relays_Get_SwitchedObj(void);
    DSS_CAPI_DLL void Relays_Set_MonitoredTerm(int32_t Value);
    DSS_CAPI_DLL void Relays_Set_SwitchedObj(char* Value);
    DSS_CAPI_DLL int32_t Relays_Get_SwitchedTerm(void);
    DSS_CAPI_DLL void Relays_Set_SwitchedTerm(int32_t Value);
    DSS_CAPI_DLL int32_t Relays_Get_idx(void);
    DSS_CAPI_DLL void Relays_Set_idx(int32_t Value);
    DSS_CAPI_DLL void Sensors_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Sensors_Get_Count(void);
    DSS_CAPI_DLL void Sensors_Get_Currents(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Sensors_Get_First(void);
    DSS_CAPI_DLL uint16_t Sensors_Get_IsDelta(void);
    DSS_CAPI_DLL void Sensors_Get_kVARS(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Sensors_Get_kVS(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Sensors_Get_kWS(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL char* Sensors_Get_MeteredElement(void);
    DSS_CAPI_DLL int32_t Sensors_Get_MeteredTerminal(void);
    DSS_CAPI_DLL char* Sensors_Get_Name(void);
    DSS_CAPI_DLL int32_t Sensors_Get_Next(void);
    DSS_CAPI_DLL double Sensors_Get_PctError(void);
    DSS_CAPI_DLL uint16_t Sensors_Get_ReverseDelta(void);
    DSS_CAPI_DLL double Sensors_Get_Weight(void);
    DSS_CAPI_DLL void Sensors_Reset(void);
    DSS_CAPI_DLL void Sensors_ResetAll(void);
    DSS_CAPI_DLL void Sensors_Set_Currents(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Sensors_Set_IsDelta(uint16_t Value);
    DSS_CAPI_DLL void Sensors_Set_kVARS(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Sensors_Set_kVS(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Sensors_Set_kWS(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Sensors_Set_MeteredElement(char* Value);
    DSS_CAPI_DLL void Sensors_Set_MeteredTerminal(int32_t Value);
    DSS_CAPI_DLL void Sensors_Set_Name(char* Value);
    DSS_CAPI_DLL void Sensors_Set_PctError(double Value);
    DSS_CAPI_DLL void Sensors_Set_ReverseDelta(uint16_t Value);
    DSS_CAPI_DLL void Sensors_Set_Weight(double Value);
    DSS_CAPI_DLL double Sensors_Get_kVbase(void);
    DSS_CAPI_DLL void Sensors_Set_kVbase(double Value);
    DSS_CAPI_DLL uint16_t Settings_Get_AllowDuplicates(void);
    DSS_CAPI_DLL char* Settings_Get_AutoBusList(void);
    DSS_CAPI_DLL int32_t Settings_Get_CktModel(void);
    DSS_CAPI_DLL double Settings_Get_EmergVmaxpu(void);
    DSS_CAPI_DLL double Settings_Get_EmergVminpu(void);
    DSS_CAPI_DLL double Settings_Get_NormVmaxpu(void);
    DSS_CAPI_DLL double Settings_Get_NormVminpu(void);
    DSS_CAPI_DLL uint16_t Settings_Get_ZoneLock(void);
    DSS_CAPI_DLL void Settings_Set_AllocationFactors(double Value);
    DSS_CAPI_DLL void Settings_Set_AllowDuplicates(uint16_t Value);
    DSS_CAPI_DLL void Settings_Set_AutoBusList(char* Value);
    DSS_CAPI_DLL void Settings_Set_CktModel(int32_t Value);
    DSS_CAPI_DLL void Settings_Set_EmergVmaxpu(double Value);
    DSS_CAPI_DLL void Settings_Set_EmergVminpu(double Value);
    DSS_CAPI_DLL void Settings_Set_NormVmaxpu(double Value);
    DSS_CAPI_DLL void Settings_Set_NormVminpu(double Value);
    DSS_CAPI_DLL void Settings_Set_ZoneLock(uint16_t Value);
    DSS_CAPI_DLL void Settings_Get_LossRegs(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Settings_Get_LossWeight(void);
    DSS_CAPI_DLL uint16_t Settings_Get_Trapezoidal(void);
    DSS_CAPI_DLL void Settings_Get_UEregs(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Settings_Get_UEweight(void);
    DSS_CAPI_DLL void Settings_Set_LossRegs(int32_t* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Settings_Set_LossWeight(double Value);
    DSS_CAPI_DLL void Settings_Set_Trapezoidal(uint16_t Value);
    DSS_CAPI_DLL void Settings_Set_UEregs(int32_t* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL void Settings_Set_UEweight(double Value);
    DSS_CAPI_DLL uint16_t Settings_Get_ControlTrace(void);
    DSS_CAPI_DLL void Settings_Get_VoltageBases(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Settings_Set_ControlTrace(uint16_t Value);
    DSS_CAPI_DLL void Settings_Set_VoltageBases(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL char* Settings_Get_PriceCurve(void);
    DSS_CAPI_DLL double Settings_Get_PriceSignal(void);
    DSS_CAPI_DLL void Settings_Set_PriceCurve(char* Value);
    DSS_CAPI_DLL void Settings_Set_PriceSignal(double Value);
    DSS_CAPI_DLL double Solution_Get_Frequency(void);
    DSS_CAPI_DLL int32_t Solution_Get_Hour(void);
    DSS_CAPI_DLL int32_t Solution_Get_Iterations(void);
    DSS_CAPI_DLL double Solution_Get_LoadMult(void);
    DSS_CAPI_DLL int32_t Solution_Get_MaxIterations(void);
    DSS_CAPI_DLL int32_t Solution_Get_Mode(void);
    DSS_CAPI_DLL int32_t Solution_Get_Number(void);
    DSS_CAPI_DLL int32_t Solution_Get_Random(void);
    DSS_CAPI_DLL double Solution_Get_Seconds(void);
    DSS_CAPI_DLL double Solution_Get_StepSize(void);
    DSS_CAPI_DLL double Solution_Get_Tolerance(void);
    DSS_CAPI_DLL int32_t Solution_Get_Year(void);
    DSS_CAPI_DLL void Solution_Set_Frequency(double Value);
    DSS_CAPI_DLL void Solution_Set_Hour(int32_t Value);
    DSS_CAPI_DLL void Solution_Set_LoadMult(double Value);
    DSS_CAPI_DLL void Solution_Set_MaxIterations(int32_t Value);
    DSS_CAPI_DLL void Solution_Set_Mode(int32_t Mode);
    DSS_CAPI_DLL void Solution_Set_Number(int32_t Value);
    DSS_CAPI_DLL void Solution_Set_Random(int32_t Random);
    DSS_CAPI_DLL void Solution_Set_Seconds(double Value);
    DSS_CAPI_DLL void Solution_Set_StepSize(double Value);
    DSS_CAPI_DLL void Solution_Set_Tolerance(double Value);
    DSS_CAPI_DLL void Solution_Set_Year(int32_t Value);
    DSS_CAPI_DLL void Solution_Solve(void);
    DSS_CAPI_DLL char* Solution_Get_ModeID(void);
    DSS_CAPI_DLL int32_t Solution_Get_LoadModel(void);
    DSS_CAPI_DLL void Solution_Set_LoadModel(int32_t Value);
    DSS_CAPI_DLL char* Solution_Get_LDCurve(void);
    DSS_CAPI_DLL void Solution_Set_LDCurve(char* Value);
    DSS_CAPI_DLL double Solution_Get_pctGrowth(void);
    DSS_CAPI_DLL void Solution_Set_pctGrowth(double Value);
    DSS_CAPI_DLL int32_t Solution_Get_AddType(void);
    DSS_CAPI_DLL void Solution_Set_AddType(int32_t Value);
    DSS_CAPI_DLL double Solution_Get_GenkW(void);
    DSS_CAPI_DLL void Solution_Set_GenkW(double Value);
    DSS_CAPI_DLL double Solution_Get_GenPF(void);
    DSS_CAPI_DLL void Solution_Set_GenPF(double Value);
    DSS_CAPI_DLL double Solution_Get_Capkvar(void);
    DSS_CAPI_DLL void Solution_Set_Capkvar(double Value);
    DSS_CAPI_DLL int32_t Solution_Get_Algorithm(void);
    DSS_CAPI_DLL void Solution_Set_Algorithm(int32_t Value);
    DSS_CAPI_DLL int32_t Solution_Get_ControlMode(void);
    DSS_CAPI_DLL void Solution_Set_ControlMode(int32_t Value);
    DSS_CAPI_DLL double Solution_Get_GenMult(void);
    DSS_CAPI_DLL void Solution_Set_GenMult(double Value);
    DSS_CAPI_DLL char* Solution_Get_DefaultDaily(void);
    DSS_CAPI_DLL char* Solution_Get_DefaultYearly(void);
    DSS_CAPI_DLL void Solution_Set_DefaultDaily(char* Value);
    DSS_CAPI_DLL void Solution_Set_DefaultYearly(char* Value);
    DSS_CAPI_DLL void Solution_Get_EventLog(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double Solution_Get_dblHour(void);
    DSS_CAPI_DLL void Solution_Set_dblHour(double Value);
    DSS_CAPI_DLL void Solution_Set_StepsizeHr(double Value);
    DSS_CAPI_DLL void Solution_Set_StepsizeMin(double Value);
    DSS_CAPI_DLL int32_t Solution_Get_ControlIterations(void);
    DSS_CAPI_DLL int32_t Solution_Get_MaxControlIterations(void);
    DSS_CAPI_DLL void Solution_Sample_DoControlActions(void);
    DSS_CAPI_DLL void Solution_Set_ControlIterations(int32_t Value);
    DSS_CAPI_DLL void Solution_Set_MaxControlIterations(int32_t Value);
    DSS_CAPI_DLL void Solution_CheckFaultStatus(void);
    DSS_CAPI_DLL void Solution_SolveDirect(void);
    DSS_CAPI_DLL void Solution_SolveNoControl(void);
    DSS_CAPI_DLL void Solution_SolvePflow(void);
    DSS_CAPI_DLL void Solution_SolvePlusControl(void);
    DSS_CAPI_DLL void Solution_SolveSnap(void);
    DSS_CAPI_DLL void Solution_CheckControls(void);
    DSS_CAPI_DLL void Solution_InitSnap(void);
    DSS_CAPI_DLL uint16_t Solution_Get_SystemYChanged(void);
    DSS_CAPI_DLL void Solution_BuildYMatrix(int32_t BuildOption, int32_t AllocateVI);
    DSS_CAPI_DLL void Solution_DoControlActions(void);
    DSS_CAPI_DLL void Solution_SampleControlDevices(void);
    DSS_CAPI_DLL uint16_t Solution_Get_Converged(void);
    DSS_CAPI_DLL void Solution_Set_Converged(uint16_t Value);
    DSS_CAPI_DLL int32_t Solution_Get_Totaliterations(void);
    DSS_CAPI_DLL int32_t Solution_Get_MostIterationsDone(void);
    DSS_CAPI_DLL uint16_t Solution_Get_ControlActionsDone(void);
    DSS_CAPI_DLL void Solution_Set_ControlActionsDone(uint16_t Value);
    DSS_CAPI_DLL void Solution_Cleanup(void);
    DSS_CAPI_DLL void Solution_FinishTimeStep(void);
    DSS_CAPI_DLL double Solution_Get_Process_Time(void);
    DSS_CAPI_DLL double Solution_Get_Total_Time(void);
    DSS_CAPI_DLL void Solution_Set_Total_Time(double Value);
    DSS_CAPI_DLL double Solution_Get_Time_of_Step(void);
    DSS_CAPI_DLL double Solution_Get_IntervalHrs(void);
    DSS_CAPI_DLL void Solution_Set_IntervalHrs(double Value);
    DSS_CAPI_DLL int32_t Solution_Get_MinIterations(void);
    DSS_CAPI_DLL void Solution_Set_MinIterations(int32_t Value);
    DSS_CAPI_DLL void Solution_SolveAll(void);
    DSS_CAPI_DLL void Solution_Get_IncMatrix(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Solution_Get_BusLevels(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Solution_Get_IncMatrixRows(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Solution_Get_IncMatrixCols(int32_t** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t SwtControls_Get_Action(void);
    DSS_CAPI_DLL void SwtControls_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL double SwtControls_Get_Delay(void);
    DSS_CAPI_DLL int32_t SwtControls_Get_First(void);
    DSS_CAPI_DLL uint16_t SwtControls_Get_IsLocked(void);
    DSS_CAPI_DLL char* SwtControls_Get_Name(void);
    DSS_CAPI_DLL int32_t SwtControls_Get_Next(void);
    DSS_CAPI_DLL char* SwtControls_Get_SwitchedObj(void);
    DSS_CAPI_DLL int32_t SwtControls_Get_SwitchedTerm(void);
    DSS_CAPI_DLL void SwtControls_Set_Action(int32_t Value);
    DSS_CAPI_DLL void SwtControls_Set_Delay(double Value);
    DSS_CAPI_DLL void SwtControls_Set_IsLocked(uint16_t Value);
    DSS_CAPI_DLL void SwtControls_Set_Name(char* Value);
    DSS_CAPI_DLL void SwtControls_Set_SwitchedObj(char* Value);
    DSS_CAPI_DLL void SwtControls_Set_SwitchedTerm(int32_t Value);
    DSS_CAPI_DLL int32_t SwtControls_Get_Count(void);
    DSS_CAPI_DLL int32_t SwtControls_Get_NormalState(void);
    DSS_CAPI_DLL void SwtControls_Set_NormalState(int32_t Value);
    DSS_CAPI_DLL int32_t SwtControls_Get_State(void);
    DSS_CAPI_DLL void SwtControls_Set_State(int32_t Value);
    DSS_CAPI_DLL void SwtControls_Reset(void);
    DSS_CAPI_DLL char* Text_Get_Command(void);
    DSS_CAPI_DLL void Text_Set_Command(char* Value);
    DSS_CAPI_DLL char* Text_Get_Result(void);
    DSS_CAPI_DLL int32_t Topology_Get_NumLoops(void);
    DSS_CAPI_DLL int32_t Topology_Get_ActiveBranch(void);
    DSS_CAPI_DLL void Topology_Get_AllIsolatedBranches(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void Topology_Get_AllLoopedPairs(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Topology_Get_BackwardBranch(void);
    DSS_CAPI_DLL char* Topology_Get_BranchName(void);
    DSS_CAPI_DLL int32_t Topology_Get_First(void);
    DSS_CAPI_DLL int32_t Topology_Get_ForwardBranch(void);
    DSS_CAPI_DLL int32_t Topology_Get_LoopedBranch(void);
    DSS_CAPI_DLL int32_t Topology_Get_Next(void);
    DSS_CAPI_DLL int32_t Topology_Get_NumIsolatedBranches(void);
    DSS_CAPI_DLL int32_t Topology_Get_ParallelBranch(void);
    DSS_CAPI_DLL void Topology_Set_BranchName(char* Value);
    DSS_CAPI_DLL void Topology_Get_AllIsolatedLoads(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Topology_Get_FirstLoad(void);
    DSS_CAPI_DLL int32_t Topology_Get_NextLoad(void);
    DSS_CAPI_DLL int32_t Topology_Get_NumIsolatedLoads(void);
    DSS_CAPI_DLL int32_t Topology_Get_ActiveLevel(void);
    DSS_CAPI_DLL char* Topology_Get_BusName(void);
    DSS_CAPI_DLL void Topology_Set_BusName(char* Value);
    DSS_CAPI_DLL void Transformers_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Transformers_Get_First(void);
    DSS_CAPI_DLL uint16_t Transformers_Get_IsDelta(void);
    DSS_CAPI_DLL double Transformers_Get_kV(void);
    DSS_CAPI_DLL double Transformers_Get_kVA(void);
    DSS_CAPI_DLL double Transformers_Get_MaxTap(void);
    DSS_CAPI_DLL double Transformers_Get_MinTap(void);
    DSS_CAPI_DLL char* Transformers_Get_Name(void);
    DSS_CAPI_DLL int32_t Transformers_Get_Next(void);
    DSS_CAPI_DLL int32_t Transformers_Get_NumTaps(void);
    DSS_CAPI_DLL int32_t Transformers_Get_NumWindings(void);
    DSS_CAPI_DLL double Transformers_Get_R(void);
    DSS_CAPI_DLL double Transformers_Get_Rneut(void);
    DSS_CAPI_DLL double Transformers_Get_Tap(void);
    DSS_CAPI_DLL int32_t Transformers_Get_Wdg(void);
    DSS_CAPI_DLL char* Transformers_Get_XfmrCode(void);
    DSS_CAPI_DLL double Transformers_Get_Xhl(void);
    DSS_CAPI_DLL double Transformers_Get_Xht(void);
    DSS_CAPI_DLL double Transformers_Get_Xlt(void);
    DSS_CAPI_DLL double Transformers_Get_Xneut(void);
    DSS_CAPI_DLL void Transformers_Set_IsDelta(uint16_t Value);
    DSS_CAPI_DLL void Transformers_Set_kV(double Value);
    DSS_CAPI_DLL void Transformers_Set_kVA(double Value);
    DSS_CAPI_DLL void Transformers_Set_MaxTap(double Value);
    DSS_CAPI_DLL void Transformers_Set_MinTap(double Value);
    DSS_CAPI_DLL void Transformers_Set_Name(char* Value);
    DSS_CAPI_DLL void Transformers_Set_NumTaps(int32_t Value);
    DSS_CAPI_DLL void Transformers_Set_NumWindings(int32_t Value);
    DSS_CAPI_DLL void Transformers_Set_R(double Value);
    DSS_CAPI_DLL void Transformers_Set_Rneut(double Value);
    DSS_CAPI_DLL void Transformers_Set_Tap(double Value);
    DSS_CAPI_DLL void Transformers_Set_Wdg(int32_t Value);
    DSS_CAPI_DLL void Transformers_Set_XfmrCode(char* Value);
    DSS_CAPI_DLL void Transformers_Set_Xhl(double Value);
    DSS_CAPI_DLL void Transformers_Set_Xht(double Value);
    DSS_CAPI_DLL void Transformers_Set_Xlt(double Value);
    DSS_CAPI_DLL void Transformers_Set_Xneut(double Value);
    DSS_CAPI_DLL int32_t Transformers_Get_Count(void);
    DSS_CAPI_DLL void Vsources_Get_AllNames(char*** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL int32_t Vsources_Get_Count(void);
    DSS_CAPI_DLL int32_t Vsources_Get_First(void);
    DSS_CAPI_DLL int32_t Vsources_Get_Next(void);
    DSS_CAPI_DLL char* Vsources_Get_Name(void);
    DSS_CAPI_DLL void Vsources_Set_Name(char* Value);
    DSS_CAPI_DLL double Vsources_Get_BasekV(void);
    DSS_CAPI_DLL double Vsources_Get_pu(void);
    DSS_CAPI_DLL void Vsources_Set_BasekV(double Value);
    DSS_CAPI_DLL void Vsources_Set_pu(double Value);
    DSS_CAPI_DLL double Vsources_Get_AngleDeg(void);
    DSS_CAPI_DLL double Vsources_Get_Frequency(void);
    DSS_CAPI_DLL int32_t Vsources_Get_Phases(void);
    DSS_CAPI_DLL void Vsources_Set_AngleDeg(double Value);
    DSS_CAPI_DLL void Vsources_Set_Frequency(double Value);
    DSS_CAPI_DLL void Vsources_Set_Phases(int32_t Value);
    DSS_CAPI_DLL int32_t XYCurves_Get_Count(void);
    DSS_CAPI_DLL int32_t XYCurves_Get_First(void);
    DSS_CAPI_DLL char* XYCurves_Get_Name(void);
    DSS_CAPI_DLL int32_t XYCurves_Get_Next(void);
    DSS_CAPI_DLL void XYCurves_Set_Name(char* Value);
    DSS_CAPI_DLL int32_t XYCurves_Get_Npts(void);
    DSS_CAPI_DLL void XYCurves_Get_Xarray(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void XYCurves_Set_Npts(int32_t Value);
    DSS_CAPI_DLL void XYCurves_Set_Xarray(double* ValuePtr, int32_t ValueCount);
    DSS_CAPI_DLL double XYCurves_Get_x(void);
    DSS_CAPI_DLL double XYCurves_Get_y(void);
    DSS_CAPI_DLL void XYCurves_Get_Yarray(double** ResultPtr, int32_t* ResultCount);
    DSS_CAPI_DLL void XYCurves_Set_x(double Value);
    DSS_CAPI_DLL void XYCurves_Set_y(double Value);
    DSS_CAPI_DLL double XYCurves_Get_Xscale(void);
    DSS_CAPI_DLL double XYCurves_Get_Xshift(void);
    DSS_CAPI_DLL double XYCurves_Get_Yscale(void);
    DSS_CAPI_DLL double XYCurves_Get_Yshift(void);
    DSS_CAPI_DLL void XYCurves_Set_Xscale(double Value);
    DSS_CAPI_DLL void XYCurves_Set_Xshift(double Value);
    DSS_CAPI_DLL void XYCurves_Set_Yscale(double Value);
    DSS_CAPI_DLL void XYCurves_Set_Yshift(double Value);

    DSSPM_CAPI_DLL void YMatrix_GetCompressedYMatrix(uint16_t factor, uint32_t *nBus, uint32_t *nNz, int32_t **ColPtr, int32_t **RowIdxPtr, double **cValsPtr);
    DSSPM_CAPI_DLL void YMatrix_ZeroInjCurr(void);
    DSSPM_CAPI_DLL void YMatrix_GetSourceInjCurrents(void);
    DSSPM_CAPI_DLL void YMatrix_GetPCInjCurr(void);
    DSSPM_CAPI_DLL void YMatrix_BuildYMatrixD(int32_t BuildOps, int32_t AllocateVI);
    DSSPM_CAPI_DLL void YMatrix_AddInAuxCurrents(int32_t SType);
    DSSPM_CAPI_DLL void YMatrix_getIpointer(double **IvectorPtr);
    DSSPM_CAPI_DLL void YMatrix_getVpointer(double **VvectorPtr);
    DSSPM_CAPI_DLL int32_t YMatrix_SolveSystem(double **NodeVPtr);
    DSSPM_CAPI_DLL void YMatrix_Set_SystemYChanged(uint16_t arg);
    DSSPM_CAPI_DLL uint16_t YMatrix_Get_SystemYChanged(void);
    DSSPM_CAPI_DLL void YMatrix_Set_UseAuxCurrents(uint16_t arg);
    DSSPM_CAPI_DLL uint16_t YMatrix_Get_UseAuxCurrents(void);
    

    enum MonitorModes {
        MonitorModes_VI = 0x00000000,
        MonitorModes_Power = 0x00000001,
        MonitorModes_Sequence = 0x00000010,
        MonitorModes_Magnitude = 0x00000020,
        MonitorModes_PosOnly = 0x00000040,
        MonitorModes_Taps = 0x00000002,
        MonitorModes_States = 0x00000003
    };

    enum SolveModes {
        SolveModes_SnapShot = 0x00000000,
        SolveModes_DutyCycle = 0x00000006,
        SolveModes_Direct = 0x00000007,
        SolveModes_Daily = 0x00000001,
        SolveModes_Monte1 = 0x00000003,
        SolveModes_Monte2 = 0x0000000A,
        SolveModes_Monte3 = 0x0000000B,
        SolveModes_FaultStudy = 0x00000009,
        SolveModes_Yearly = 0x00000002,
        SolveModes_MonteFault = 0x00000008,
        SolveModes_PeakDay = 0x00000005,
        SolveModes_LD1 = 0x00000004,
        SolveModes_LD2 = 0x0000000C,
        SolveModes_AutoAdd = 0x0000000D,
        SolveModes_Harmonic = 0x0000000F,
        SolveModes_Dynamic = 0x0000000E
    };

    enum Options {
        Options_PowerFlow = 0x00000001,
        Options_Admittance = 0x00000002,
        Options_NormalSolve = 0x00000000,
        Options_NewtonSolve = 0x00000001,
        Options_Static = 0x00000000,
        Options_Event = 0x00000001,
        Options_Time = 0x00000002,
        Options_Multiphase = 0x00000000,
        Options_PositiveSeq = 0x00000001,
        Options_Gaussian = 0x00000001,
        Options_Uniform = 0x00000002,
        Options_LogNormal = 0x00000003,
        Options_AddGen = 0x00000001,
        Options_AddCap = 0x00000002,
        Options_ControlOFF = 0xFFFFFFFF
    };

    enum CapControlModes {
        CapControlModes_Voltage = 0x00000001,
        CapControlModes_KVAR = 0x00000002,
        CapControlModes_Current = 0x00000000,
        CapControlModes_PF = 0x00000004,
        CapControlModes_Time = 0x00000003
    };

    enum ActionCodes {
        ActionCodes_none = 0x00000000,
        ActionCodes_Open = 0x00000001,
        ActionCodes_Close = 0x00000002,
        ActionCodes_Reset = 0x00000003,
        ActionCodes_Lock = 0x00000004,
        ActionCodes_Unlock = 0x00000005,
        ActionCodes_TapUp = 0x00000006,
        ActionCodes_TapDown = 0x00000007
    };

    enum LoadStatus {
        LoadStatus_Variable = 0x00000000,
        LoadStatus_Fixed = 0x00000001,
        LoadStatus_Exempt = 0x00000002
    };

    enum LoadModels {
        LoadModels_ConstPQ = 0x00000001,
        LoadModels_ConstZ = 0x00000002,
        LoadModels_Motor = 0x00000003,
        LoadModels_CVR = 0x00000004,
        LoadModels_ConstI = 0x00000005,
        LoadModels_ConstPFixedQ = 0x00000006,
        LoadModels_ConstPFixedX = 0x00000007,
        LoadModels_ZIPV = 0x00000008
    };

    enum LineUnits {
        LineUnits_none = 0x00000000,
        LineUnits_Miles = 0x00000001,
        LineUnits_kFt = 0x00000002,
        LineUnits_km = 0x00000003,
        LineUnits_meter = 0x00000004,
        LineUnits_ft = 0x00000005,
        LineUnits_inch = 0x00000006,
        LineUnits_cm = 0x00000007,
        LineUnits_mm = 0x00000008,
        LineUnits_Maxnum = 0x00000009
    };

#ifdef __cplusplus
}
#endif
#endif
