name: Builds

#TODO: Windows ARM, Windows matrix-based setup after we move from Free Pascal

on: 
  # release:
  #   types: [created]
  push:

jobs:
  build_linux:
    name: 'Linux ${{ matrix.arch }}'
    continue-on-error: false
    strategy:
      matrix:
        include:
          - arch: x64
            docker_image: 'pmeira/manylinux_wheel_fpc322_x86_64'
            extra_cmake_flags: ''
            dss_extensions_linux32: ''
            gh_image: ubuntu-latest
          - arch: x86
            docker_image: 'pmeira/manylinux_wheel_fpc322_i686'
            extra_cmake_flags: '-DCMAKE_CXX_COMPILER_ARG1=-m32 -DCMAKE_C_COMPILER_ARG1=-m32'
            dss_extensions_linux32: linux32
            gh_image: ubuntu-latest
          - arch: arm64
            docker_image: 'pmeira/manylinux_wheel_fpc322_aarch64'
            extra_cmake_flags: ''
            dss_extensions_linux32: ''
            gh_image: ubuntu-24.04-arm

    runs-on: ${{ matrix.gh_image }}
    env:
      KLUSOLVE_URL: 'https://github.com/dss-extensions/klusolve/releases/download/1.2.2/klusolvex_1.2.2_linux_${{ matrix.arch }}.tar.gz'
      DSS_CAPI_BUILD_CMAKE: '1'
      DOCKER_IMAGE: ${{ matrix.docker_image }}
      DSS_EXTENSIONS_LINUX32: ${{ matrix.dss_extensions_linux32 }}
      DSS_EXTENSIONS_EXTRA_CMAKE_FLAGS: ${{ matrix.extra_cmake_flags }}
    steps: 
      - name: 'Checkout'
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY dss_capi
          cd dss_capi
          git checkout $GITHUB_SHA
      - name: 'Setup Docker'
        run: |
          docker pull $DOCKER_IMAGE
      - name: 'Download/extract KLUSolve(X)'
        run: |
          curl -s -L "${KLUSOLVE_URL}" -o klusolve.tar.gz
          tar zxf klusolve.tar.gz
          mkdir -p dss_capi/lib/linux_${{ matrix.arch }}
          cp -r klusolvex/lib/* dss_capi/lib/
      - name: Build
        run: |
          cd dss_capi
          source ./build/make_metadata.sh
          docker run -e DSS_CAPI_VERSION -e DSS_CAPI_BUILD_CMAKE -v "${PWD}/..:/build" $DOCKER_IMAGE bash -c 'cd /build/dss_capi; PATH=/opt/python/cp38-cp38/bin/:$PATH ${DSS_EXTENSIONS_LINUX32} bash build/build_linux_${{ matrix.arch }}.sh'
          ls -lR lib
      - name: 'Upload artifacts'
        uses: "actions/upload-artifact@v4"
        #if: github.event_name == 'release' && github.event.action == 'created'
        with:
          name: 'development-build-linux_${{ matrix.arch }}'
          path: '${{ github.workspace }}/dss_capi/release/*.tar.gz'

  build_macos:
    name: 'macOS ${{ matrix.arch }}'
    continue-on-error: false
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            arch: x64
            extra_cmake_flags: '-DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0'
          - os: macos-15
            arch: arm64
            extra_cmake_flags: '-DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0'

    runs-on: ${{ matrix.os }}
    env:
      DSS_CAPI_BUILD_CMAKE: '1'
      MACOSX_DEPLOYMENT_TARGET: '11.0'
      DSS_EXTENSIONS_EXTRA_CMAKE_FLAGS: ${{ matrix.extra_cmake_flags }}
    steps:
      - uses: "actions/checkout@v4"
        with: 
          fetch-depth: 0
          path: 'dss_capi'
      - name: 'Install FreePascal'
        run: |
          wget https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.2.2/fpc-3.2.2.intelarm64-macosx.dmg/download -Ofpc.dmg -q
          sudo hdiutil attach fpc.dmg
          sudo installer -package /Volumes/fpc-3.2.2.intelarm64-macosx/fpc-3.2.2-intelarm64-macosx.mpkg -target /
      - name: 'Download/extract KLUSolve(X)'
        run: |
          wget "https://github.com/dss-extensions/klusolve/releases/download/1.2.2/klusolvex_1.2.2_darwin_${{ matrix.arch }}.tar.gz" -Oklusolve.tar.gz -q
          tar zxf klusolve.tar.gz
          mkdir -p dss_capi/lib/darwin_${{ matrix.arch }}
          cp -r klusolvex/lib/* dss_capi/lib/
      - name: Build
        run: |
          cd dss_capi
          source ./build/make_metadata.sh
          ./build/build_macos_${{ matrix.arch }}.sh
          ls -lR lib
      - name: 'Upload artifacts'
        uses: "actions/upload-artifact@v4"
        #if: github.event_name == 'release' && github.event.action == 'created'
        with:
          name: 'development-build-darwin-${{ matrix.arch }}'
          path: '${{ github.workspace }}/dss_capi/release/*.tar.gz'

  build_win_x64:
    name: 'Windows x64'
    continue-on-error: false
    runs-on: windows-2022
    env: 
      DSS_CAPI_BUILD_CMAKE: '1'
    steps:
      - uses: "actions/checkout@v4"
        with: 
          fetch-depth: 0
          path: 'dss_capi'
      - name: 'Install FreePascal'
        shell: cmd
        run: |
          "c:\Program Files\Git\mingw64\bin\curl" -s -L https://sourceforge.net/projects/freepascal/files/Win32/3.2.2/fpc-3.2.2.i386-win32.exe/download -o fpc-win32.exe
          "c:\Program Files\Git\mingw64\bin\curl" -s -L https://sourceforge.net/projects/freepascal/files/Win32/3.2.2/fpc-3.2.2.i386-win32.cross.x86_64-win64.exe/download -o fpc-win32.cross.x86_64-win64.exe
          fpc-win32.exe /VERYSILENT
          fpc-win32.cross.x86_64-win64.exe /VERYSILENT
      - name: 'Download/extract KLUSolve(X)'
        shell: cmd
        run: |
          "c:\Program Files\Git\mingw64\bin\curl" -s -L https://github.com/dss-extensions/klusolve/releases/download/1.2.2/klusolvex_1.2.2_windows_x64_gcc_windows-2022.zip -o klusolve_x64.zip
          7z x -y -o. klusolve_x64.zip
          mkdir dss_capi\lib
          mkdir dss_capi\lib\win_x64
          xcopy /E klusolvex\lib dss_capi\lib
      - name: Prepare MSBUILD
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build
        #TODO? cv2pdb (generate PDB for MSVC) and dlltool (generate lib compatible with GCC)
        shell: cmd
        run: |
          cd dss_capi
          "c:\Program Files\Git\bin\bash" -c "bash ./build/make_metadata.sh write"
          set PATH=%PATH%;C:\FPC\3.2.2\bin\i386-win32
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call build/generated/set_version.bat
          call build/build_win_x64.bat
      - name: 'Upload artifacts'
        uses: "actions/upload-artifact@v4"
        #if: github.event_name == 'release' && github.event.action == 'created'
        with:
          name: 'development-build-win_x64'
          path: '${{ github.workspace }}/dss_capi/release/*.zip'

  build_win_x86:
    name: 'Windows x86'
    continue-on-error: false
    runs-on: windows-2022
    env: 
      DSS_CAPI_BUILD_CMAKE: '1'
    steps:
      - uses: "actions/checkout@v4"
        with: 
          fetch-depth: 0
          path: 'dss_capi'
      - name: 'Install FreePascal'
        shell: cmd
        run: |
          "c:\Program Files\Git\mingw64\bin\curl" -s -L https://sourceforge.net/projects/freepascal/files/Win32/3.2.2/fpc-3.2.2.i386-win32.exe/download -o fpc-win32.exe
          fpc-win32.exe /VERYSILENT
      - name: 'Download KLUSolve(X)'
        shell: cmd
        run: |
          "c:\Program Files\Git\mingw64\bin\curl" -s -L https://github.com/dss-extensions/klusolve/releases/download/1.2.2/klusolvex_1.2.2_windows_x86_msvc_windows-2022.zip -o klusolve_x86.zip
      - name: 'Extract KLUSolve(X)'
        shell: cmd
        run: |
          7z x -y -o. klusolve_x86.zip
          mkdir dss_capi\lib
          mkdir dss_capi\lib\win_x86
          xcopy /E klusolvex\lib dss_capi\lib
      - name: Prepare MSBUILD
        uses: microsoft/setup-msbuild@v2
      - name: Build
        #TODO? cv2pdb (generate PDB for MSVC) and dlltool (generate lib compatible with GCC)
        shell: cmd
        run: |
          cd dss_capi
          "c:\Program Files\Git\bin\bash" -c "bash ./build/make_metadata.sh write"
          set PATH=%PATH%;C:\FPC\3.2.2\bin\i386-win32
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          call build/generated/set_version.bat
          call build/build_win_x86.bat
      - name: 'Upload artifacts'
        uses: "actions/upload-artifact@v4"
        #if: github.event_name == 'release' && github.event.action == 'created'
        with:
          name: 'development-build-win_x86'
          path: '${{ github.workspace }}/dss_capi/release/*.zip'

  merge:
    runs-on: ubuntu-latest
    needs: [build_linux, build_macos, build_win_x64, build_win_x86]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: development-build
          pattern: development-build-*
          # delete-merged: true

